<?php

    namespace Database\Seeders\Market;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class MarketList extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        DB::table('market_lists')->insert([
//        //Gia dat quan 1 - 2020.
//            ['MarketID'=> 1, 'DistrictName'=> 'Quận 1', 'WardName'=>'Bến Nghé', 'Year'=>'2020',
//             'Thang_1'=>750, 'Thang_2'=>725, 'Thang_3'=>800, 'Thang_4'=>825,
//             'Thang_5'=>775, 'Thang_6'=>800, 'Thang_7'=>850, 'Thang_8'=>900,
//             'Thang_9'=>950, 'Thang_10'=>935, 'Thang_11'=>800, 'Thang_12'=>990,
//                ],
//            ['MarketID'=> 2, 'DistrictName'=> 'Quận 1', 'WardName'=>'Bến Thành', 'Year'=>'2020',
//                'Thang_1'=>650, 'Thang_2'=>625, 'Thang_3'=>700, 'Thang_4'=>725,
//                'Thang_5'=>675, 'Thang_6'=>750, 'Thang_7'=>700, 'Thang_8'=>800,
//                'Thang_9'=>850, 'Thang_10'=>835, 'Thang_11'=>790, 'Thang_12'=>890,
//            ],
//            ['MarketID'=> 3, 'DistrictName'=> 'Quận 1', 'WardName'=>'Cầu Kho', 'Year'=>'2020',
//                'Thang_1'=>250, 'Thang_2'=>225, 'Thang_3'=>280, 'Thang_4'=>225,
//                'Thang_5'=>275, 'Thang_6'=>300, 'Thang_7'=>250, 'Thang_8'=>300,
//                'Thang_9'=>275, 'Thang_10'=>235, 'Thang_11'=>335, 'Thang_12'=>350,
//            ],
//            ['MarketID'=> 4, 'DistrictName'=> 'Quận 1', 'WardName'=>'Cầu Ông Lãnh', 'Year'=>'2020',
//                'Thang_1'=>300, 'Thang_2'=>325, 'Thang_3'=>350, 'Thang_4'=>325,
//                'Thang_5'=>295, 'Thang_6'=>300, 'Thang_7'=>350, 'Thang_8'=>330,
//                'Thang_9'=>300, 'Thang_10'=>315, 'Thang_11'=>310, 'Thang_12'=>320,
//            ],
//            ['MarketID'=> 5, 'DistrictName'=> 'Quận 1', 'WardName'=>'Cô Giang', 'Year'=>'2020',
//                'Thang_1'=>200, 'Thang_2'=>225, 'Thang_3'=>215, 'Thang_4'=>235,
//                'Thang_5'=>220, 'Thang_6'=>240, 'Thang_7'=>225, 'Thang_8'=>250,
//                'Thang_9'=>265, 'Thang_10'=>255, 'Thang_11'=>250, 'Thang_12'=>245,
//            ],
//            ['MarketID'=> 6, 'DistrictName'=> 'Quận 1', 'WardName'=>'Đa Kao', 'Year'=>'2020',
//                'Thang_1'=>300, 'Thang_2'=>325, 'Thang_3'=>315, 'Thang_4'=>335,
//                'Thang_5'=>320, 'Thang_6'=>340, 'Thang_7'=>325, 'Thang_8'=>350,
//                'Thang_9'=>365, 'Thang_10'=>355, 'Thang_11'=>350, 'Thang_12'=>345,
//            ],
//            ['MarketID'=> 7, 'DistrictName'=> 'Quận 1', 'WardName'=>'Nguyễn Cư Trinh', 'Year'=>'2020',
//                'Thang_1'=>320, 'Thang_2'=>345, 'Thang_3'=>335, 'Thang_4'=>335,
//                'Thang_5'=>320, 'Thang_6'=>340, 'Thang_7'=>325, 'Thang_8'=>350,
//                'Thang_9'=>365, 'Thang_10'=>355, 'Thang_11'=>350, 'Thang_12'=>355,
//            ],
//            ['MarketID'=> 8, 'DistrictName'=> 'Quận 1', 'WardName'=>'Nguyễn Thái Bình', 'Year'=>'2020',
//                'Thang_1'=>520, 'Thang_2'=>545, 'Thang_3'=>555, 'Thang_4'=>535,
//                'Thang_5'=>590, 'Thang_6'=>580, 'Thang_7'=>595, 'Thang_8'=>605,
//                'Thang_9'=>615, 'Thang_10'=>605, 'Thang_11'=>620, 'Thang_12'=>635,
//            ],
//            ['MarketID'=> 9, 'DistrictName'=> 'Quận 1', 'WardName'=>'Phạm Ngũ Lão', 'Year'=>'2020',
//                'Thang_1'=>430, 'Thang_2'=>425, 'Thang_3'=>415, 'Thang_4'=>435,
//                'Thang_5'=>440, 'Thang_6'=>423, 'Thang_7'=>452, 'Thang_8'=>440,
//                'Thang_9'=>455, 'Thang_10'=>445, 'Thang_11'=>463, 'Thang_12'=>473,
//            ],
//            ['MarketID'=> 10, 'DistrictName'=> 'Quận 1', 'WardName'=>'Tân Định', 'Year'=>'2020',
//                'Thang_1'=>232, 'Thang_2'=>223, 'Thang_3'=>241, 'Thang_4'=>233,
//                'Thang_5'=>247, 'Thang_6'=>231, 'Thang_7'=>237, 'Thang_8'=>253,
//                'Thang_9'=>262, 'Thang_10'=>271, 'Thang_11'=>260, 'Thang_12'=>275,
//            ],

//        //Gia dat quan 2 - 2020.
//            ['MarketID'=> 11, 'DistrictName'=> 'Quận 2', 'WardName'=>'An Khánh', 'Year'=>'2020',
//                'Thang_1'=>68, 'Thang_2'=>75, 'Thang_3'=>63, 'Thang_4'=>55,
//                'Thang_5'=>60, 'Thang_6'=>63, 'Thang_7'=>68, 'Thang_8'=>75,
//                'Thang_9'=>72, 'Thang_10'=>69, 'Thang_11'=>71, 'Thang_12'=>77,
//            ],
//            ['MarketID'=> 12, 'DistrictName'=> 'Quận 2', 'WardName'=>'An Lợi Đông', 'Year'=>'2020',
//                'Thang_1'=>91, 'Thang_2'=>88, 'Thang_3'=>83, 'Thang_4'=>88,
//                'Thang_5'=>89, 'Thang_6'=>94, 'Thang_7'=>100, 'Thang_8'=>97,
//                'Thang_9'=>103, 'Thang_10'=>99, 'Thang_11'=>94, 'Thang_12'=>105,
//            ],
//            ['MarketID'=> 13, 'DistrictName'=> 'Quận 2', 'WardName'=>'An Phú', 'Year'=>'2020',
//                'Thang_1'=>93, 'Thang_2'=>103, 'Thang_3'=>103, 'Thang_4'=>107,
//                'Thang_5'=>115, 'Thang_6'=>108, 'Thang_7'=>103, 'Thang_8'=>111,
//                'Thang_9'=>117, 'Thang_10'=>123, 'Thang_11'=>130, 'Thang_12'=>114,
//            ],
//            ['MarketID'=> 14, 'DistrictName'=> 'Quận 2', 'WardName'=>'Bình An', 'Year'=>'2020',
//                'Thang_1'=>135, 'Thang_2'=>132, 'Thang_3'=>127, 'Thang_4'=>131,
//                'Thang_5'=>139, 'Thang_6'=>142, 'Thang_7'=>145, 'Thang_8'=>133,
//                'Thang_9'=>129, 'Thang_10'=>271, 'Thang_11'=>134, 'Thang_12'=>143,
//            ],
//            ['MarketID'=> 15, 'DistrictName'=> 'Quận 2', 'WardName'=>'Bình Khánh', 'Year'=>'2020',
//                'Thang_1'=>55, 'Thang_2'=>53, 'Thang_3'=>57, 'Thang_4'=>59,
//                'Thang_5'=>51, 'Thang_6'=>54, 'Thang_7'=>65, 'Thang_8'=>62,
//                'Thang_9'=>72, 'Thang_10'=>75, 'Thang_11'=>65, 'Thang_12'=>61,
//            ],
//            ['MarketID'=> 16, 'DistrictName'=> 'Quận 2', 'WardName'=>'Bình Trưng Đông', 'Year'=>'2020',
//                'Thang_1'=>63, 'Thang_2'=>59, 'Thang_3'=>61, 'Thang_4'=>65,
//                'Thang_5'=>71, 'Thang_6'=>68, 'Thang_7'=>61, 'Thang_8'=>56,
//                'Thang_9'=>69, 'Thang_10'=>73, 'Thang_11'=>79, 'Thang_12'=>71,
//            ],
//            ['MarketID'=> 17, 'DistrictName'=> 'Quận 2', 'WardName'=>'Bình Trưng Tây', 'Year'=>'2020',
//                'Thang_1'=>64, 'Thang_2'=>72, 'Thang_3'=>77, 'Thang_4'=>83,
//                'Thang_5'=>79, 'Thang_6'=>71, 'Thang_7'=>75, 'Thang_8'=>68,
//                'Thang_9'=>70, 'Thang_10'=>72, 'Thang_11'=>75, 'Thang_12'=>77,
//            ],
//            ['MarketID'=> 18, 'DistrictName'=> 'Quận 2', 'WardName'=>'Cát Lái', 'Year'=>'2020',
//                'Thang_1'=>67, 'Thang_2'=>73, 'Thang_3'=>78, 'Thang_4'=>82,
//                'Thang_5'=>63, 'Thang_6'=>65, 'Thang_7'=>69, 'Thang_8'=>61,
//                'Thang_9'=>66, 'Thang_10'=>73, 'Thang_11'=>75, 'Thang_12'=>69,
//            ],
//            ['MarketID'=> 19, 'DistrictName'=> 'Quận 2', 'WardName'=>'Thạnh Mỹ Lợi', 'Year'=>'2020',
//                'Thang_1'=>72, 'Thang_2'=>75, 'Thang_3'=>77, 'Thang_4'=>83,
//                'Thang_5'=>71, 'Thang_6'=>67, 'Thang_7'=>73, 'Thang_8'=>79,
//                'Thang_9'=>81, 'Thang_10'=>75, 'Thang_11'=>71, 'Thang_12'=>81,
//            ],
//            ['MarketID'=> 20, 'DistrictName'=> 'Quận 2', 'WardName'=>'Thảo Điền', 'Year'=>'2020',
//                'Thang_1'=>111, 'Thang_2'=>107, 'Thang_3'=>101, 'Thang_4'=>99,
//                'Thang_5'=>115, 'Thang_6'=>119, 'Thang_7'=>121, 'Thang_8'=>125,
//                'Thang_9'=>132, 'Thang_10'=>122, 'Thang_11'=>115, 'Thang_12'=>124,
//            ],
//            ['MarketID'=> 21, 'DistrictName'=> 'Quận 2', 'WardName'=>'Thủ Thiêm', 'Year'=>'2020',
//                'Thang_1'=>128, 'Thang_2'=>122, 'Thang_3'=>125, 'Thang_4'=>117,
//                'Thang_5'=>135, 'Thang_6'=>133, 'Thang_7'=>139, 'Thang_8'=>142,
//                'Thang_9'=>145, 'Thang_10'=>141, 'Thang_11'=>133, 'Thang_12'=>145,
//            ],
//
//            //Gia dat quan 3 - 2020.
//            ['MarketID'=> 23, 'DistrictName'=> 'Quận 3', 'WardName'=>'Phường 01', 'Year'=>'2020',
//                'Thang_1'=>245, 'Thang_2'=>243, 'Thang_3'=>236, 'Thang_4'=>238,
//                'Thang_5'=>255, 'Thang_6'=>263, 'Thang_7'=>245, 'Thang_8'=>253,
//                'Thang_9'=>241, 'Thang_10'=>245, 'Thang_11'=>248, 'Thang_12'=>259,
//            ],
//            ['MarketID'=> 24, 'DistrictName'=> 'Quận 3', 'WardName'=>'Phường 02', 'Year'=>'2020',
//                'Thang_1'=>330, 'Thang_2'=>333, 'Thang_3'=>323, 'Thang_4'=>315,
//                'Thang_5'=>337, 'Thang_6'=>341, 'Thang_7'=>345, 'Thang_8'=>353,
//                'Thang_9'=>341, 'Thang_10'=>332, 'Thang_11'=>329, 'Thang_12'=>345,
//            ],
//            ['MarketID'=> 25, 'DistrictName'=> 'Quận 3', 'WardName'=>'Phường 03', 'Year'=>'2020',
//                'Thang_1'=>240, 'Thang_2'=>233, 'Thang_3'=>221, 'Thang_4'=>236,
//                'Thang_5'=>243, 'Thang_6'=>252, 'Thang_7'=>262, 'Thang_8'=>252,
//                'Thang_9'=>255, 'Thang_10'=>251, 'Thang_11'=>241, 'Thang_12'=>263,
//            ],
//            ['MarketID'=> 26, 'DistrictName'=> 'Quận 3', 'WardName'=>'Phường 04', 'Year'=>'2020',
//                'Thang_1'=>208, 'Thang_2'=>201, 'Thang_3'=>213, 'Thang_4'=>217,
//                'Thang_5'=>222, 'Thang_6'=>231, 'Thang_7'=>237, 'Thang_8'=>243,
//                'Thang_9'=>234, 'Thang_10'=>231, 'Thang_11'=>221, 'Thang_12'=>242,
//            ],
//            ['MarketID'=> 27, 'DistrictName'=> 'Quận 3', 'WardName'=>'Phường 05', 'Year'=>'2020',
//                'Thang_1'=>303, 'Thang_2'=>309, 'Thang_3'=>315, 'Thang_4'=>321,
//                'Thang_5'=>333, 'Thang_6'=>322, 'Thang_7'=>325, 'Thang_8'=>327,
//                'Thang_9'=>333, 'Thang_10'=>341, 'Thang_11'=>346, 'Thang_12'=>341,
//            ],
//            ['MarketID'=> 28, 'DistrictName'=> 'Quận 3', 'WardName'=>'Phường 06', 'Year'=>'2020',
//                'Thang_1'=>372, 'Thang_2'=>379, 'Thang_3'=>382, 'Thang_4'=>385,
//                'Thang_5'=>365, 'Thang_6'=>361, 'Thang_7'=>369, 'Thang_8'=>372,
//                'Thang_9'=>381, 'Thang_10'=>391, 'Thang_11'=>393, 'Thang_12'=>393,
//            ],
//            ['MarketID'=> 29, 'DistrictName'=> 'Quận 3', 'WardName'=>'Phường 07', 'Year'=>'2020',
//                'Thang_1'=>239, 'Thang_2'=>233, 'Thang_3'=>242, 'Thang_4'=>234,
//                'Thang_5'=>230, 'Thang_6'=>235, 'Thang_7'=>241, 'Thang_8'=>245,
//                'Thang_9'=>254, 'Thang_10'=>245, 'Thang_11'=>235, 'Thang_12'=>243,
//            ],
//            ['MarketID'=> 30, 'DistrictName'=> 'Quận 3', 'WardName'=>'Phường 08', 'Year'=>'2020',
//                'Thang_1'=>222, 'Thang_2'=>223, 'Thang_3'=>215, 'Thang_4'=>232,
//                'Thang_5'=>237, 'Thang_6'=>240, 'Thang_7'=>231, 'Thang_8'=>235,
//                'Thang_9'=>237, 'Thang_10'=>222, 'Thang_11'=>229, 'Thang_12'=>233,
//            ],
//            ['MarketID'=> 31, 'DistrictName'=> 'Quận 3', 'WardName'=>'Phường 09', 'Year'=>'2020',
//                'Thang_1'=>214, 'Thang_2'=>204, 'Thang_3'=>209, 'Thang_4'=>211,
//                'Thang_5'=>235, 'Thang_6'=>222, 'Thang_7'=>226, 'Thang_8'=>231,
//                'Thang_9'=>237, 'Thang_10'=>223, 'Thang_11'=>233, 'Thang_12'=>239,
//            ],
//            ['MarketID'=> 32, 'DistrictName'=> 'Quận 3', 'WardName'=>'Phường 10', 'Year'=>'2020',
//                'Thang_1'=>197, 'Thang_2'=>203, 'Thang_3'=>213, 'Thang_4'=>223,
//                'Thang_5'=>201, 'Thang_6'=>199, 'Thang_7'=>206, 'Thang_8'=>215,
//                'Thang_9'=>221, 'Thang_10'=>214, 'Thang_11'=>203, 'Thang_12'=>218,
//            ],
//            ['MarketID'=> 33, 'DistrictName'=> 'Quận 3', 'WardName'=>'Phường 11', 'Year'=>'2020',
//                'Thang_1'=>152, 'Thang_2'=>159, 'Thang_3'=>163, 'Thang_4'=>168,
//                'Thang_5'=>153, 'Thang_6'=>155, 'Thang_7'=>147, 'Thang_8'=>159,
//                'Thang_9'=>161, 'Thang_10'=>153, 'Thang_11'=>157, 'Thang_12'=>165,
//            ],
//            ['MarketID'=> 34, 'DistrictName'=> 'Quận 2', 'WardName'=>'Phường 12', 'Year'=>'2020',
//                'Thang_1'=>173, 'Thang_2'=>179, 'Thang_3'=>182, 'Thang_4'=>191,
//                'Thang_5'=>195, 'Thang_6'=>178, 'Thang_7'=>173, 'Thang_8'=>162,
//                'Thang_9'=>175, 'Thang_10'=>180, 'Thang_11'=>183, 'Thang_12'=>181,
//            ],
//            ['MarketID'=> 35, 'DistrictName'=> 'Quận 3', 'WardName'=>'Phường 13', 'Year'=>'2020',
//                'Thang_1'=>231, 'Thang_2'=>223, 'Thang_3'=>235, 'Thang_4'=>241,
//                'Thang_5'=>247, 'Thang_6'=>243, 'Thang_7'=>239, 'Thang_8'=>233,
//                'Thang_9'=>241, 'Thang_10'=>245, 'Thang_11'=>251, 'Thang_12'=>259,
//            ],
//            ['MarketID'=> 36, 'DistrictName'=> 'Quận 3', 'WardName'=>'Phường 14', 'Year'=>'2020',
//                'Thang_1'=>198, 'Thang_2'=>204, 'Thang_3'=>213, 'Thang_4'=>223,
//                'Thang_5'=>211, 'Thang_6'=>201, 'Thang_7'=>215, 'Thang_8'=>220,
//                'Thang_9'=>231, 'Thang_10'=>227, 'Thang_11'=>225, 'Thang_12'=>231,
//            ],

            //Gia dat quan 4 - 2020: chưa edit.
            ['MarketID'=> 37, 'DistrictName'=> 'Quận 4', 'WardName'=>'Phường 01', 'Year'=>'2020',
                'Thang_1'=>random_int(225, 255), 'Thang_2'=>random_int(225, 255), 'Thang_3'=>random_int(225, 255), 'Thang_4'=>random_int(225, 255),
                'Thang_5'=>random_int(225, 255), 'Thang_6'=>random_int(225, 255), 'Thang_7'=>random_int(225, 255), 'Thang_8'=>random_int(225, 255),
                'Thang_9'=>random_int(225, 255), 'Thang_10'=>random_int(225, 255), 'Thang_11'=>random_int(225, 255), 'Thang_12'=>random_int(225, 255),
            ],
            ['MarketID'=> 38, 'DistrictName'=> 'Quận 4', 'WardName'=>'Phường 02', 'Year'=>'2020',
                'Thang_1'=>random_int(), 'Thang_2'=>, 'Thang_3'=>, 'Thang_4'=>,
                'Thang_5'=>, 'Thang_6'=>, 'Thang_7'=>, 'Thang_8'=>,
                'Thang_9'=>, 'Thang_10'=>, 'Thang_11'=>, 'Thang_12'=>,
            ],
            ['MarketID'=> 39, 'DistrictName'=> 'Quận 4', 'WardName'=>'Phường 03', 'Year'=>'2020',
                'Thang_1'=>random_int(), 'Thang_2'=>, 'Thang_3'=>, 'Thang_4'=>,
                'Thang_5'=>, 'Thang_6'=>, 'Thang_7'=>, 'Thang_8'=>,
                'Thang_9'=>, 'Thang_10'=>, 'Thang_11'=>, 'Thang_12'=>,
            ],
            ['MarketID'=> 40, 'DistrictName'=> 'Quận 4', 'WardName'=>'Phường 04', 'Year'=>'2020',
                'Thang_1'=>random_int(), 'Thang_2'=>, 'Thang_3'=>, 'Thang_4'=>,
                'Thang_5'=>, 'Thang_6'=>, 'Thang_7'=>, 'Thang_8'=>,
                'Thang_9'=>, 'Thang_10'=>, 'Thang_11'=>, 'Thang_12'=>,
            ],
            ['MarketID'=> 41, 'DistrictName'=> 'Quận 4', 'WardName'=>'Phường 05', 'Year'=>'2020',
                'Thang_1'=>random_int(), 'Thang_2'=>, 'Thang_3'=>, 'Thang_4'=>,
                'Thang_5'=>, 'Thang_6'=>, 'Thang_7'=>, 'Thang_8'=>,
                'Thang_9'=>, 'Thang_10'=>, 'Thang_11'=>, 'Thang_12'=>,
            ],
            ['MarketID'=> 42, 'DistrictName'=> 'Quận 4', 'WardName'=>'Phường 06', 'Year'=>'2020',
                'Thang_1'=>random_int(), 'Thang_2'=>, 'Thang_3'=>, 'Thang_4'=>,
                'Thang_5'=>, 'Thang_6'=>, 'Thang_7'=>, 'Thang_8'=>,
                'Thang_9'=>, 'Thang_10'=>, 'Thang_11'=>, 'Thang_12'=>,
            ],
            ['MarketID'=> 43, 'DistrictName'=> 'Quận 4', 'WardName'=>'Phường 07', 'Year'=>'2020',
                'Thang_1'=>random_int(), 'Thang_2'=>, 'Thang_3'=>, 'Thang_4'=>,
                'Thang_5'=>, 'Thang_6'=>, 'Thang_7'=>, 'Thang_8'=>,
                'Thang_9'=>, 'Thang_10'=>, 'Thang_11'=>, 'Thang_12'=>,
            ],
            ['MarketID'=> 44, 'DistrictName'=> 'Quận 4', 'WardName'=>'Phường 08', 'Year'=>'2020',
                'Thang_1'=>random_int(), 'Thang_2'=>, 'Thang_3'=>, 'Thang_4'=>,
                'Thang_5'=>, 'Thang_6'=>, 'Thang_7'=>, 'Thang_8'=>,
                'Thang_9'=>, 'Thang_10'=>, 'Thang_11'=>, 'Thang_12'=>,
            ],
            ['MarketID'=> 45, 'DistrictName'=> 'Quận 4', 'WardName'=>'Phường 09', 'Year'=>'2020',
                'Thang_1'=>random_int(), 'Thang_2'=>, 'Thang_3'=>, 'Thang_4'=>,
                'Thang_5'=>, 'Thang_6'=>, 'Thang_7'=>, 'Thang_8'=>,
                'Thang_9'=>, 'Thang_10'=>, 'Thang_11'=>, 'Thang_12'=>,
            ],
            ['MarketID'=> 46, 'DistrictName'=> 'Quận 4', 'WardName'=>'Phường 10', 'Year'=>'2020',
                'Thang_1'=>random_int(), 'Thang_2'=>, 'Thang_3'=>, 'Thang_4'=>,
                'Thang_5'=>, 'Thang_6'=>, 'Thang_7'=>, 'Thang_8'=>,
                'Thang_9'=>, 'Thang_10'=>, 'Thang_11'=>, 'Thang_12'=>,
            ],
            ['MarketID'=> 47, 'DistrictName'=> 'Quận 4', 'WardName'=>'Phường 11', 'Year'=>'2020',
                'Thang_1'=>random_int(), 'Thang_2'=>, 'Thang_3'=>, 'Thang_4'=>,
                'Thang_5'=>, 'Thang_6'=>, 'Thang_7'=>, 'Thang_8'=>,
                'Thang_9'=>, 'Thang_10'=>, 'Thang_11'=>, 'Thang_12'=>,
            ],
            ['MarketID'=> 48, 'DistrictName'=> 'Quận 4', 'WardName'=>'Phường 12', 'Year'=>'2020',
                'Thang_1'=>random_int(), 'Thang_2'=>, 'Thang_3'=>, 'Thang_4'=>,
                'Thang_5'=>, 'Thang_6'=>, 'Thang_7'=>, 'Thang_8'=>,
                'Thang_9'=>, 'Thang_10'=>, 'Thang_11'=>, 'Thang_12'=>,
            ],
            ['MarketID'=> 49, 'DistrictName'=> 'Quận 4', 'WardName'=>'Phường 13', 'Year'=>'2020',
                'Thang_1'=>random_int(), 'Thang_2'=>, 'Thang_3'=>, 'Thang_4'=>,
                'Thang_5'=>, 'Thang_6'=>, 'Thang_7'=>, 'Thang_8'=>,
                'Thang_9'=>, 'Thang_10'=>, 'Thang_11'=>, 'Thang_12'=>,
            ],
            ['MarketID'=> 50, 'DistrictName'=> 'Quận 4', 'WardName'=>'Phường 14', 'Year'=>'2020',
                'Thang_1'=>random_int(), 'Thang_2'=>, 'Thang_3'=>, 'Thang_4'=>,
                'Thang_5'=>, 'Thang_6'=>, 'Thang_7'=>, 'Thang_8'=>,
                'Thang_9'=>, 'Thang_10'=>, 'Thang_11'=>, 'Thang_12'=>,
            ],
            ['MarketID'=> 51, 'DistrictName'=> 'Quận 4', 'WardName'=>'Phường 15', 'Year'=>'2020',
                'Thang_1'=>random_int(), 'Thang_2'=>, 'Thang_3'=>, 'Thang_4'=>,
                'Thang_5'=>, 'Thang_6'=>, 'Thang_7'=>, 'Thang_8'=>,
                'Thang_9'=>, 'Thang_10'=>, 'Thang_11'=>, 'Thang_12'=>,
            ],
            ['MarketID'=> 52, 'DistrictName'=> 'Quận 4', 'WardName'=>'Phường 16', 'Year'=>'2020',
                'Thang_1'=>random_int(), 'Thang_2'=>, 'Thang_3'=>, 'Thang_4'=>,
                'Thang_5'=>, 'Thang_6'=>, 'Thang_7'=>, 'Thang_8'=>,
                'Thang_9'=>, 'Thang_10'=>, 'Thang_11'=>, 'Thang_12'=>,
            ],
            ['MarketID'=> 53, 'DistrictName'=> 'Quận 4', 'WardName'=>'Phường 17', 'Year'=>'2020',
                'Thang_1'=>random_int(), 'Thang_2'=>, 'Thang_3'=>, 'Thang_4'=>,
                'Thang_5'=>, 'Thang_6'=>, 'Thang_7'=>, 'Thang_8'=>,
                'Thang_9'=>, 'Thang_10'=>, 'Thang_11'=>, 'Thang_12'=>,
            ],
            ['MarketID'=> 54, 'DistrictName'=> 'Quận 4', 'WardName'=>'Phường 18', 'Year'=>'2020',
                'Thang_1'=>random_int(), 'Thang_2'=>, 'Thang_3'=>, 'Thang_4'=>,
                'Thang_5'=>, 'Thang_6'=>, 'Thang_7'=>, 'Thang_8'=>,
                'Thang_9'=>, 'Thang_10'=>, 'Thang_11'=>, 'Thang_12'=>,
            ],

            //Gia dat quan 5 - 2020: chưa edit.
            ['MarketID'=> 55, 'DistrictName'=> 'Quận 5', 'WardName'=>'Phường 01', 'Year'=>'2020',
                'Thang_1'=>random_int(), 'Thang_2'=>, 'Thang_3'=>, 'Thang_4'=>,
                'Thang_5'=>, 'Thang_6'=>, 'Thang_7'=>, 'Thang_8'=>,
                'Thang_9'=>, 'Thang_10'=>, 'Thang_11'=>, 'Thang_12'=>,
            ],
            ['MarketID'=> 56, 'DistrictName'=> 'Quận 5', 'WardName'=>'Phường 02', 'Year'=>'2020',
                'Thang_1'=>random_int(), 'Thang_2'=>, 'Thang_3'=>, 'Thang_4'=>,
                'Thang_5'=>, 'Thang_6'=>, 'Thang_7'=>, 'Thang_8'=>,
                'Thang_9'=>, 'Thang_10'=>, 'Thang_11'=>, 'Thang_12'=>,
            ],
            ['MarketID'=> 57, 'DistrictName'=> 'Quận 5', 'WardName'=>'Phường 03', 'Year'=>'2020',
                'Thang_1'=>random_int(), 'Thang_2'=>, 'Thang_3'=>, 'Thang_4'=>,
                'Thang_5'=>, 'Thang_6'=>, 'Thang_7'=>, 'Thang_8'=>,
                'Thang_9'=>, 'Thang_10'=>, 'Thang_11'=>, 'Thang_12'=>,
            ],
            ['MarketID'=> 58, 'DistrictName'=> 'Quận 5', 'WardName'=>'Phường 04', 'Year'=>'2020',
                'Thang_1'=>random_int(), 'Thang_2'=>, 'Thang_3'=>, 'Thang_4'=>,
                'Thang_5'=>, 'Thang_6'=>, 'Thang_7'=>, 'Thang_8'=>,
                'Thang_9'=>, 'Thang_10'=>, 'Thang_11'=>, 'Thang_12'=>,
            ],
            ['MarketID'=> 59, 'DistrictName'=> 'Quận 5', 'WardName'=>'Phường 05', 'Year'=>'2020',
                'Thang_1'=>random_int(), 'Thang_2'=>, 'Thang_3'=>, 'Thang_4'=>,
                'Thang_5'=>, 'Thang_6'=>, 'Thang_7'=>, 'Thang_8'=>,
                'Thang_9'=>, 'Thang_10'=>, 'Thang_11'=>, 'Thang_12'=>,
            ],
            ['MarketID'=> 60, 'DistrictName'=> 'Quận 5', 'WardName'=>'Phường 06', 'Year'=>'2020',
                'Thang_1'=>random_int(), 'Thang_2'=>, 'Thang_3'=>, 'Thang_4'=>,
                'Thang_5'=>, 'Thang_6'=>, 'Thang_7'=>, 'Thang_8'=>,
                'Thang_9'=>, 'Thang_10'=>, 'Thang_11'=>, 'Thang_12'=>,
            ],
            ['MarketID'=> 61, 'DistrictName'=> 'Quận 5', 'WardName'=>'Phường 07', 'Year'=>'2020',
                'Thang_1'=>random_int(), 'Thang_2'=>, 'Thang_3'=>, 'Thang_4'=>,
                'Thang_5'=>, 'Thang_6'=>, 'Thang_7'=>, 'Thang_8'=>,
                'Thang_9'=>, 'Thang_10'=>, 'Thang_11'=>, 'Thang_12'=>,
            ],
            ['MarketID'=> 62, 'DistrictName'=> 'Quận 5', 'WardName'=>'Phường 08', 'Year'=>'2020',
                'Thang_1'=>random_int(), 'Thang_2'=>, 'Thang_3'=>, 'Thang_4'=>,
                'Thang_5'=>, 'Thang_6'=>, 'Thang_7'=>, 'Thang_8'=>,
                'Thang_9'=>, 'Thang_10'=>, 'Thang_11'=>, 'Thang_12'=>,
            ],
            ['MarketID'=> 63, 'DistrictName'=> 'Quận 5', 'WardName'=>'Phường 09', 'Year'=>'2020',
                'Thang_1'=>random_int(), 'Thang_2'=>, 'Thang_3'=>, 'Thang_4'=>,
                'Thang_5'=>, 'Thang_6'=>, 'Thang_7'=>, 'Thang_8'=>,
                'Thang_9'=>, 'Thang_10'=>, 'Thang_11'=>, 'Thang_12'=>,
            ],
            ['MarketID'=> 64, 'DistrictName'=> 'Quận 5', 'WardName'=>'Phường 10', 'Year'=>'2020',
                'Thang_1'=>random_int(), 'Thang_2'=>, 'Thang_3'=>, 'Thang_4'=>,
                'Thang_5'=>, 'Thang_6'=>, 'Thang_7'=>, 'Thang_8'=>,
                'Thang_9'=>, 'Thang_10'=>, 'Thang_11'=>, 'Thang_12'=>,
            ],
            ['MarketID'=> 65, 'DistrictName'=> 'Quận 5', 'WardName'=>'Phường 11', 'Year'=>'2020',
                'Thang_1'=>random_int(), 'Thang_2'=>, 'Thang_3'=>, 'Thang_4'=>,
                'Thang_5'=>, 'Thang_6'=>, 'Thang_7'=>, 'Thang_8'=>,
                'Thang_9'=>, 'Thang_10'=>, 'Thang_11'=>, 'Thang_12'=>,
            ],
            ['MarketID'=> 66, 'DistrictName'=> 'Quận 5', 'WardName'=>'Phường 12', 'Year'=>'2020',
                'Thang_1'=>random_int(), 'Thang_2'=>, 'Thang_3'=>, 'Thang_4'=>,
                'Thang_5'=>, 'Thang_6'=>, 'Thang_7'=>, 'Thang_8'=>,
                'Thang_9'=>, 'Thang_10'=>, 'Thang_11'=>, 'Thang_12'=>,
            ],
            ['MarketID'=> 67, 'DistrictName'=> 'Quận 5', 'WardName'=>'Phường 13', 'Year'=>'2020',
                'Thang_1'=>random_int(), 'Thang_2'=>, 'Thang_3'=>, 'Thang_4'=>,
                'Thang_5'=>, 'Thang_6'=>, 'Thang_7'=>, 'Thang_8'=>,
                'Thang_9'=>, 'Thang_10'=>, 'Thang_11'=>, 'Thang_12'=>,
            ],
            ['MarketID'=> 68, 'DistrictName'=> 'Quận 5', 'WardName'=>'Phường 14', 'Year'=>'2020',
                'Thang_1'=>random_int(), 'Thang_2'=>, 'Thang_3'=>, 'Thang_4'=>,
                'Thang_5'=>, 'Thang_6'=>, 'Thang_7'=>, 'Thang_8'=>,
                'Thang_9'=>, 'Thang_10'=>, 'Thang_11'=>, 'Thang_12'=>,
            ],
            ['MarketID'=> 69, 'DistrictName'=> 'Quận 5', 'WardName'=>'Phường 15', 'Year'=>'2020',
                'Thang_1'=>random_int(), 'Thang_2'=>, 'Thang_3'=>, 'Thang_4'=>,
                'Thang_5'=>, 'Thang_6'=>, 'Thang_7'=>, 'Thang_8'=>,
                'Thang_9'=>, 'Thang_10'=>, 'Thang_11'=>, 'Thang_12'=>,
            ],

            //Gia dat quan 6 - 2020: chưa edit.
            ['MarketID'=> 70, 'DistrictName'=> 'Quận 6', 'WardName'=>'Phường 01', 'Year'=>'2020',
                'Thang_1'=>random_int(), 'Thang_2'=>, 'Thang_3'=>, 'Thang_4'=>,
                'Thang_5'=>, 'Thang_6'=>, 'Thang_7'=>, 'Thang_8'=>,
                'Thang_9'=>, 'Thang_10'=>, 'Thang_11'=>, 'Thang_12'=>,
            ],
            ['MarketID'=> 71, 'DistrictName'=> 'Quận 6', 'WardName'=>'Phường 02', 'Year'=>'2020',
                'Thang_1'=>random_int(), 'Thang_2'=>, 'Thang_3'=>, 'Thang_4'=>,
                'Thang_5'=>, 'Thang_6'=>, 'Thang_7'=>, 'Thang_8'=>,
                'Thang_9'=>, 'Thang_10'=>, 'Thang_11'=>, 'Thang_12'=>,
            ],
            ['MarketID'=> 72, 'DistrictName'=> 'Quận 6', 'WardName'=>'Phường 03', 'Year'=>'2020',
                'Thang_1'=>random_int(), 'Thang_2'=>, 'Thang_3'=>, 'Thang_4'=>,
                'Thang_5'=>, 'Thang_6'=>, 'Thang_7'=>, 'Thang_8'=>,
                'Thang_9'=>, 'Thang_10'=>, 'Thang_11'=>, 'Thang_12'=>,
            ],
            ['MarketID'=> 73, 'DistrictName'=> 'Quận 6', 'WardName'=>'Phường 04', 'Year'=>'2020',
                'Thang_1'=>random_int(), 'Thang_2'=>, 'Thang_3'=>, 'Thang_4'=>,
                'Thang_5'=>, 'Thang_6'=>, 'Thang_7'=>, 'Thang_8'=>,
                'Thang_9'=>, 'Thang_10'=>, 'Thang_11'=>, 'Thang_12'=>,
            ],
            ['MarketID'=> 74, 'DistrictName'=> 'Quận 6', 'WardName'=>'Phường 05', 'Year'=>'2020',
                'Thang_1'=>random_int(), 'Thang_2'=>, 'Thang_3'=>, 'Thang_4'=>,
                'Thang_5'=>, 'Thang_6'=>, 'Thang_7'=>, 'Thang_8'=>,
                'Thang_9'=>, 'Thang_10'=>, 'Thang_11'=>, 'Thang_12'=>,
            ],
            ['MarketID'=> 75, 'DistrictName'=> 'Quận 6', 'WardName'=>'Phường 06', 'Year'=>'2020',
                'Thang_1'=>random_int(), 'Thang_2'=>, 'Thang_3'=>, 'Thang_4'=>,
                'Thang_5'=>, 'Thang_6'=>, 'Thang_7'=>, 'Thang_8'=>,
                'Thang_9'=>, 'Thang_10'=>, 'Thang_11'=>, 'Thang_12'=>,
            ],
            ['MarketID'=> 76, 'DistrictName'=> 'Quận 6', 'WardName'=>'Phường 07', 'Year'=>'2020',
                'Thang_1'=>random_int(), 'Thang_2'=>, 'Thang_3'=>, 'Thang_4'=>,
                'Thang_5'=>, 'Thang_6'=>, 'Thang_7'=>, 'Thang_8'=>,
                'Thang_9'=>, 'Thang_10'=>, 'Thang_11'=>, 'Thang_12'=>,
            ],
            ['MarketID'=> 77, 'DistrictName'=> 'Quận 6', 'WardName'=>'Phường 08', 'Year'=>'2020',
                'Thang_1'=>random_int(), 'Thang_2'=>, 'Thang_3'=>, 'Thang_4'=>,
                'Thang_5'=>, 'Thang_6'=>, 'Thang_7'=>, 'Thang_8'=>,
                'Thang_9'=>, 'Thang_10'=>, 'Thang_11'=>, 'Thang_12'=>,
            ],
            ['MarketID'=> 78, 'DistrictName'=> 'Quận 6', 'WardName'=>'Phường 09', 'Year'=>'2020',
                'Thang_1'=>random_int(), 'Thang_2'=>, 'Thang_3'=>, 'Thang_4'=>,
                'Thang_5'=>, 'Thang_6'=>, 'Thang_7'=>, 'Thang_8'=>,
                'Thang_9'=>, 'Thang_10'=>, 'Thang_11'=>, 'Thang_12'=>,
            ],
            ['MarketID'=> 79, 'DistrictName'=> 'Quận 6', 'WardName'=>'Phường 10', 'Year'=>'2020',
                'Thang_1'=>random_int(), 'Thang_2'=>, 'Thang_3'=>, 'Thang_4'=>,
                'Thang_5'=>, 'Thang_6'=>, 'Thang_7'=>, 'Thang_8'=>,
                'Thang_9'=>, 'Thang_10'=>, 'Thang_11'=>, 'Thang_12'=>,
            ],
            ['MarketID'=> 80, 'DistrictName'=> 'Quận 6', 'WardName'=>'Phường 11', 'Year'=>'2020',
                'Thang_1'=>random_int(), 'Thang_2'=>, 'Thang_3'=>, 'Thang_4'=>,
                'Thang_5'=>, 'Thang_6'=>, 'Thang_7'=>, 'Thang_8'=>,
                'Thang_9'=>, 'Thang_10'=>, 'Thang_11'=>, 'Thang_12'=>,
            ],
            ['MarketID'=> 81, 'DistrictName'=> 'Quận 6', 'WardName'=>'Phường 12', 'Year'=>'2020',
                'Thang_1'=>random_int(), 'Thang_2'=>, 'Thang_3'=>, 'Thang_4'=>,
                'Thang_5'=>, 'Thang_6'=>, 'Thang_7'=>, 'Thang_8'=>,
                'Thang_9'=>, 'Thang_10'=>, 'Thang_11'=>, 'Thang_12'=>,
            ],
            ['MarketID'=> 82, 'DistrictName'=> 'Quận 6', 'WardName'=>'Phường 13', 'Year'=>'2020',
                'Thang_1'=>random_int(), 'Thang_2'=>, 'Thang_3'=>, 'Thang_4'=>,
                'Thang_5'=>, 'Thang_6'=>, 'Thang_7'=>, 'Thang_8'=>,
                'Thang_9'=>, 'Thang_10'=>, 'Thang_11'=>, 'Thang_12'=>,
            ],
            ['MarketID'=> 83, 'DistrictName'=> 'Quận 6', 'WardName'=>'Phường 14', 'Year'=>'2020',
                'Thang_1'=>random_int(), 'Thang_2'=>, 'Thang_3'=>, 'Thang_4'=>,
                'Thang_5'=>, 'Thang_6'=>, 'Thang_7'=>, 'Thang_8'=>,
                'Thang_9'=>, 'Thang_10'=>, 'Thang_11'=>, 'Thang_12'=>,
            ],

            //Gia dat quan 7 - 2020: chưa edit.
            ['MarketID'=> 84, 'DistrictName'=> 'Quận 7', 'WardName'=>'Bình Thuận', 'Year'=>'2020',
                'Thang_1'=>random_int(), 'Thang_2'=>, 'Thang_3'=>, 'Thang_4'=>,
                'Thang_5'=>, 'Thang_6'=>, 'Thang_7'=>, 'Thang_8'=>,
                'Thang_9'=>, 'Thang_10'=>, 'Thang_11'=>, 'Thang_12'=>,
            ],
            ['MarketID'=> 85, 'DistrictName'=> 'Quận 7', 'WardName'=>'Phú Mỹ', 'Year'=>'2020',
                'Thang_1'=>random_int(), 'Thang_2'=>, 'Thang_3'=>, 'Thang_4'=>,
                'Thang_5'=>, 'Thang_6'=>, 'Thang_7'=>, 'Thang_8'=>,
                'Thang_9'=>, 'Thang_10'=>, 'Thang_11'=>, 'Thang_12'=>,
            ],
            ['MarketID'=> 86, 'DistrictName'=> 'Quận 7', 'WardName'=>'Phú Thuận', 'Year'=>'2020',
                'Thang_1'=>random_int(), 'Thang_2'=>, 'Thang_3'=>, 'Thang_4'=>,
                'Thang_5'=>, 'Thang_6'=>, 'Thang_7'=>, 'Thang_8'=>,
                'Thang_9'=>, 'Thang_10'=>, 'Thang_11'=>, 'Thang_12'=>,
            ],
            ['MarketID'=> 87, 'DistrictName'=> 'Quận 7', 'WardName'=>'Tân Hưng', 'Year'=>'2020',
                'Thang_1'=>random_int(), 'Thang_2'=>, 'Thang_3'=>, 'Thang_4'=>,
                'Thang_5'=>, 'Thang_6'=>, 'Thang_7'=>, 'Thang_8'=>,
                'Thang_9'=>, 'Thang_10'=>, 'Thang_11'=>, 'Thang_12'=>,
            ],
            ['MarketID'=> 88, 'DistrictName'=> 'Quận 7', 'WardName'=>'Tân Kiểng', 'Year'=>'2020',
                'Thang_1'=>random_int(), 'Thang_2'=>, 'Thang_3'=>, 'Thang_4'=>,
                'Thang_5'=>, 'Thang_6'=>, 'Thang_7'=>, 'Thang_8'=>,
                'Thang_9'=>, 'Thang_10'=>, 'Thang_11'=>, 'Thang_12'=>,
            ],
            ['MarketID'=> 89, 'DistrictName'=> 'Quận 7', 'WardName'=>'Tân Phong', 'Year'=>'2020',
                'Thang_1'=>random_int(), 'Thang_2'=>, 'Thang_3'=>, 'Thang_4'=>,
                'Thang_5'=>, 'Thang_6'=>, 'Thang_7'=>, 'Thang_8'=>,
                'Thang_9'=>, 'Thang_10'=>, 'Thang_11'=>, 'Thang_12'=>,
            ],
            ['MarketID'=> 90, 'DistrictName'=> 'Quận 7', 'WardName'=>'Tân Phú', 'Year'=>'2020',
                'Thang_1'=>random_int(), 'Thang_2'=>, 'Thang_3'=>, 'Thang_4'=>,
                'Thang_5'=>, 'Thang_6'=>, 'Thang_7'=>, 'Thang_8'=>,
                'Thang_9'=>, 'Thang_10'=>, 'Thang_11'=>, 'Thang_12'=>,
            ],
            ['MarketID'=> 91, 'DistrictName'=> 'Quận 7', 'WardName'=>'Tân Quy', 'Year'=>'2020',
                'Thang_1'=>random_int(), 'Thang_2'=>, 'Thang_3'=>, 'Thang_4'=>,
                'Thang_5'=>, 'Thang_6'=>, 'Thang_7'=>, 'Thang_8'=>,
                'Thang_9'=>, 'Thang_10'=>, 'Thang_11'=>, 'Thang_12'=>,
            ],
            ['MarketID'=> 92, 'DistrictName'=> 'Quận 7', 'WardName'=>'Tân Thuận Đông', 'Year'=>'2020',
                'Thang_1'=>random_int(), 'Thang_2'=>, 'Thang_3'=>, 'Thang_4'=>,
                'Thang_5'=>, 'Thang_6'=>, 'Thang_7'=>, 'Thang_8'=>,
                'Thang_9'=>, 'Thang_10'=>, 'Thang_11'=>, 'Thang_12'=>,
            ],
            ['MarketID'=> 93, 'DistrictName'=> 'Quận 7', 'WardName'=>'Tân Thuận Tây', 'Year'=>'2020',
                'Thang_1'=>random_int(), 'Thang_2'=>, 'Thang_3'=>, 'Thang_4'=>,
                'Thang_5'=>, 'Thang_6'=>, 'Thang_7'=>, 'Thang_8'=>,
                'Thang_9'=>, 'Thang_10'=>, 'Thang_11'=>, 'Thang_12'=>,
            ],

            //Gia dat quan 8 - 2020: chưa edit.
            ['MarketID'=> 94, 'DistrictName'=> 'Quận 8', 'WardName'=>'Phường 01', 'Year'=>'2020',
                'Thang_1'=>random_int(), 'Thang_2'=>, 'Thang_3'=>, 'Thang_4'=>,
                'Thang_5'=>, 'Thang_6'=>, 'Thang_7'=>, 'Thang_8'=>,
                'Thang_9'=>, 'Thang_10'=>, 'Thang_11'=>, 'Thang_12'=>,
            ],
            ['MarketID'=> 95, 'DistrictName'=> 'Quận 8', 'WardName'=>'Phường 02', 'Year'=>'2020',
                'Thang_1'=>random_int(), 'Thang_2'=>, 'Thang_3'=>, 'Thang_4'=>,
                'Thang_5'=>, 'Thang_6'=>, 'Thang_7'=>, 'Thang_8'=>,
                'Thang_9'=>, 'Thang_10'=>, 'Thang_11'=>, 'Thang_12'=>,
            ],
            ['MarketID'=> 96, 'DistrictName'=> 'Quận 8', 'WardName'=>'Phường 03', 'Year'=>'2020',
                'Thang_1'=>random_int(), 'Thang_2'=>, 'Thang_3'=>, 'Thang_4'=>,
                'Thang_5'=>, 'Thang_6'=>, 'Thang_7'=>, 'Thang_8'=>,
                'Thang_9'=>, 'Thang_10'=>, 'Thang_11'=>, 'Thang_12'=>,
            ],
            ['MarketID'=> 97, 'DistrictName'=> 'Quận 8', 'WardName'=>'Phường 04', 'Year'=>'2020',
                'Thang_1'=>random_int(), 'Thang_2'=>, 'Thang_3'=>, 'Thang_4'=>,
                'Thang_5'=>, 'Thang_6'=>, 'Thang_7'=>, 'Thang_8'=>,
                'Thang_9'=>, 'Thang_10'=>, 'Thang_11'=>, 'Thang_12'=>,
            ],
            ['MarketID'=> 98, 'DistrictName'=> 'Quận 8', 'WardName'=>'Phường 05', 'Year'=>'2020',
                'Thang_1'=>random_int(), 'Thang_2'=>, 'Thang_3'=>, 'Thang_4'=>,
                'Thang_5'=>, 'Thang_6'=>, 'Thang_7'=>, 'Thang_8'=>,
                'Thang_9'=>, 'Thang_10'=>, 'Thang_11'=>, 'Thang_12'=>,
            ],
            ['MarketID'=> 99, 'DistrictName'=> 'Quận 8', 'WardName'=>'Phường 06', 'Year'=>'2020',
                'Thang_1'=>random_int(), 'Thang_2'=>, 'Thang_3'=>, 'Thang_4'=>,
                'Thang_5'=>, 'Thang_6'=>, 'Thang_7'=>, 'Thang_8'=>,
                'Thang_9'=>, 'Thang_10'=>, 'Thang_11'=>, 'Thang_12'=>,
            ],
            ['MarketID'=> 100, 'DistrictName'=> 'Quận 8', 'WardName'=>'Phường 07', 'Year'=>'2020',
                'Thang_1'=>random_int(), 'Thang_2'=>, 'Thang_3'=>, 'Thang_4'=>,
                'Thang_5'=>, 'Thang_6'=>, 'Thang_7'=>, 'Thang_8'=>,
                'Thang_9'=>, 'Thang_10'=>, 'Thang_11'=>, 'Thang_12'=>,
            ],
            ['MarketID'=> 101, 'DistrictName'=> 'Quận 8', 'WardName'=>'Phường 08', 'Year'=>'2020',
                'Thang_1'=>random_int(), 'Thang_2'=>, 'Thang_3'=>, 'Thang_4'=>,
                'Thang_5'=>, 'Thang_6'=>, 'Thang_7'=>, 'Thang_8'=>,
                'Thang_9'=>, 'Thang_10'=>, 'Thang_11'=>, 'Thang_12'=>,
            ],
            ['MarketID'=> 102, 'DistrictName'=> 'Quận 8', 'WardName'=>'Phường 09', 'Year'=>'2020',
                'Thang_1'=>random_int(), 'Thang_2'=>, 'Thang_3'=>, 'Thang_4'=>,
                'Thang_5'=>, 'Thang_6'=>, 'Thang_7'=>, 'Thang_8'=>,
                'Thang_9'=>, 'Thang_10'=>, 'Thang_11'=>, 'Thang_12'=>,
            ],
            ['MarketID'=> 103, 'DistrictName'=> 'Quận 8', 'WardName'=>'Phường 10', 'Year'=>'2020',
                'Thang_1'=>random_int(), 'Thang_2'=>, 'Thang_3'=>, 'Thang_4'=>,
                'Thang_5'=>, 'Thang_6'=>, 'Thang_7'=>, 'Thang_8'=>,
                'Thang_9'=>, 'Thang_10'=>, 'Thang_11'=>, 'Thang_12'=>,
            ],
            ['MarketID'=> 104, 'DistrictName'=> 'Quận 8', 'WardName'=>'Phường 11', 'Year'=>'2020',
                'Thang_1'=>random_int(), 'Thang_2'=>, 'Thang_3'=>, 'Thang_4'=>,
                'Thang_5'=>, 'Thang_6'=>, 'Thang_7'=>, 'Thang_8'=>,
                'Thang_9'=>, 'Thang_10'=>, 'Thang_11'=>, 'Thang_12'=>,
            ],
            ['MarketID'=> 105, 'DistrictName'=> 'Quận 8', 'WardName'=>'Phường 12', 'Year'=>'2020',
                'Thang_1'=>random_int(), 'Thang_2'=>, 'Thang_3'=>, 'Thang_4'=>,
                'Thang_5'=>, 'Thang_6'=>, 'Thang_7'=>, 'Thang_8'=>,
                'Thang_9'=>, 'Thang_10'=>, 'Thang_11'=>, 'Thang_12'=>,
            ],
            ['MarketID'=> 106, 'DistrictName'=> 'Quận 8', 'WardName'=>'Phường 13', 'Year'=>'2020',
                'Thang_1'=>random_int(), 'Thang_2'=>, 'Thang_3'=>, 'Thang_4'=>,
                'Thang_5'=>, 'Thang_6'=>, 'Thang_7'=>, 'Thang_8'=>,
                'Thang_9'=>, 'Thang_10'=>, 'Thang_11'=>, 'Thang_12'=>,
            ],
            ['MarketID'=> 107, 'DistrictName'=> 'Quận 8', 'WardName'=>'Phường 14', 'Year'=>'2020',
                'Thang_1'=>random_int(), 'Thang_2'=>, 'Thang_3'=>, 'Thang_4'=>,
                'Thang_5'=>, 'Thang_6'=>, 'Thang_7'=>, 'Thang_8'=>,
                'Thang_9'=>, 'Thang_10'=>, 'Thang_11'=>, 'Thang_12'=>,
            ],
            ['MarketID'=> 108, 'DistrictName'=> 'Quận 8', 'WardName'=>'Phường 15', 'Year'=>'2020',
                'Thang_1'=>random_int(), 'Thang_2'=>, 'Thang_3'=>, 'Thang_4'=>,
                'Thang_5'=>, 'Thang_6'=>, 'Thang_7'=>, 'Thang_8'=>,
                'Thang_9'=>, 'Thang_10'=>, 'Thang_11'=>, 'Thang_12'=>,
            ],
            ['MarketID'=> 109, 'DistrictName'=> 'Quận 8', 'WardName'=>'Phường 16', 'Year'=>'2020',
                'Thang_1'=>random_int(), 'Thang_2'=>, 'Thang_3'=>, 'Thang_4'=>,
                'Thang_5'=>, 'Thang_6'=>, 'Thang_7'=>, 'Thang_8'=>,
                'Thang_9'=>, 'Thang_10'=>, 'Thang_11'=>, 'Thang_12'=>,
            ],

            //Gia dat quan 10 - chua edit:
            ['MarketID'=> 110, 'DistrictName'=> 'Quận 10', 'WardName'=>'Phường 01', 'Year'=>'2020',
                'Thang_1'=>random_int(), 'Thang_2'=>, 'Thang_3'=>, 'Thang_4'=>,
                'Thang_5'=>, 'Thang_6'=>, 'Thang_7'=>, 'Thang_8'=>,
                'Thang_9'=>, 'Thang_10'=>, 'Thang_11'=>, 'Thang_12'=>,
            ],
            ['MarketID'=> 111, 'DistrictName'=> 'Quận 10', 'WardName'=>'Phường 02', 'Year'=>'2020',
                'Thang_1'=>random_int(), 'Thang_2'=>, 'Thang_3'=>, 'Thang_4'=>,
                'Thang_5'=>, 'Thang_6'=>, 'Thang_7'=>, 'Thang_8'=>,
                'Thang_9'=>, 'Thang_10'=>, 'Thang_11'=>, 'Thang_12'=>,
            ],
            ['MarketID'=> 112, 'DistrictName'=> 'Quận 10', 'WardName'=>'Phường 03', 'Year'=>'2020',
                'Thang_1'=>random_int(), 'Thang_2'=>, 'Thang_3'=>, 'Thang_4'=>,
                'Thang_5'=>, 'Thang_6'=>, 'Thang_7'=>, 'Thang_8'=>,
                'Thang_9'=>, 'Thang_10'=>, 'Thang_11'=>, 'Thang_12'=>,
            ],
            ['MarketID'=> 113, 'DistrictName'=> 'Quận 10', 'WardName'=>'Phường 04', 'Year'=>'2020',
                'Thang_1'=>random_int(), 'Thang_2'=>, 'Thang_3'=>, 'Thang_4'=>,
                'Thang_5'=>, 'Thang_6'=>, 'Thang_7'=>, 'Thang_8'=>,
                'Thang_9'=>, 'Thang_10'=>, 'Thang_11'=>, 'Thang_12'=>,
            ],
            ['MarketID'=> 114, 'DistrictName'=> 'Quận 10', 'WardName'=>'Phường 05', 'Year'=>'2020',
                'Thang_1'=>random_int(), 'Thang_2'=>, 'Thang_3'=>, 'Thang_4'=>,
                'Thang_5'=>, 'Thang_6'=>, 'Thang_7'=>, 'Thang_8'=>,
                'Thang_9'=>, 'Thang_10'=>, 'Thang_11'=>, 'Thang_12'=>,
            ],
            ['MarketID'=> 115, 'DistrictName'=> 'Quận 10', 'WardName'=>'Phường 06', 'Year'=>'2020',
                'Thang_1'=>random_int(), 'Thang_2'=>, 'Thang_3'=>, 'Thang_4'=>,
                'Thang_5'=>, 'Thang_6'=>, 'Thang_7'=>, 'Thang_8'=>,
                'Thang_9'=>, 'Thang_10'=>, 'Thang_11'=>, 'Thang_12'=>,
            ],
            ['MarketID'=> 116, 'DistrictName'=> 'Quận 10', 'WardName'=>'Phường 07', 'Year'=>'2020',
                'Thang_1'=>random_int(), 'Thang_2'=>, 'Thang_3'=>, 'Thang_4'=>,
                'Thang_5'=>, 'Thang_6'=>, 'Thang_7'=>, 'Thang_8'=>,
                'Thang_9'=>, 'Thang_10'=>, 'Thang_11'=>, 'Thang_12'=>,
            ],
            ['MarketID'=> 117, 'DistrictName'=> 'Quận 10', 'WardName'=>'Phường 08', 'Year'=>'2020',
                'Thang_1'=>random_int(), 'Thang_2'=>, 'Thang_3'=>, 'Thang_4'=>,
                'Thang_5'=>, 'Thang_6'=>, 'Thang_7'=>, 'Thang_8'=>,
                'Thang_9'=>, 'Thang_10'=>, 'Thang_11'=>, 'Thang_12'=>,
            ],
            ['MarketID'=> 118, 'DistrictName'=> 'Quận 10', 'WardName'=>'Phường 09', 'Year'=>'2020',
                'Thang_1'=>random_int(), 'Thang_2'=>, 'Thang_3'=>, 'Thang_4'=>,
                'Thang_5'=>, 'Thang_6'=>, 'Thang_7'=>, 'Thang_8'=>,
                'Thang_9'=>, 'Thang_10'=>, 'Thang_11'=>, 'Thang_12'=>,
            ],
            ['MarketID'=> 119, 'DistrictName'=> 'Quận 10', 'WardName'=>'Phường 10', 'Year'=>'2020',
                'Thang_1'=>random_int(), 'Thang_2'=>, 'Thang_3'=>, 'Thang_4'=>,
                'Thang_5'=>, 'Thang_6'=>, 'Thang_7'=>, 'Thang_8'=>,
                'Thang_9'=>, 'Thang_10'=>, 'Thang_11'=>, 'Thang_12'=>,
            ],
            ['MarketID'=> 120, 'DistrictName'=> 'Quận 10', 'WardName'=>'Phường 11', 'Year'=>'2020',
                'Thang_1'=>random_int(), 'Thang_2'=>, 'Thang_3'=>, 'Thang_4'=>,
                'Thang_5'=>, 'Thang_6'=>, 'Thang_7'=>, 'Thang_8'=>,
                'Thang_9'=>, 'Thang_10'=>, 'Thang_11'=>, 'Thang_12'=>,
            ],
            ['MarketID'=> 121, 'DistrictName'=> 'Quận 10', 'WardName'=>'Phường 12', 'Year'=>'2020',
                'Thang_1'=>random_int(), 'Thang_2'=>, 'Thang_3'=>, 'Thang_4'=>,
                'Thang_5'=>, 'Thang_6'=>, 'Thang_7'=>, 'Thang_8'=>,
                'Thang_9'=>, 'Thang_10'=>, 'Thang_11'=>, 'Thang_12'=>,
            ],
            ['MarketID'=> 122, 'DistrictName'=> 'Quận 10', 'WardName'=>'Phường 13', 'Year'=>'2020',
                'Thang_1'=>random_int(), 'Thang_2'=>, 'Thang_3'=>, 'Thang_4'=>,
                'Thang_5'=>, 'Thang_6'=>, 'Thang_7'=>, 'Thang_8'=>,
                'Thang_9'=>, 'Thang_10'=>, 'Thang_11'=>, 'Thang_12'=>,
            ],
            ['MarketID'=> 123, 'DistrictName'=> 'Quận 10', 'WardName'=>'Phường 14', 'Year'=>'2020',
                'Thang_1'=>random_int(), 'Thang_2'=>, 'Thang_3'=>, 'Thang_4'=>,
                'Thang_5'=>, 'Thang_6'=>, 'Thang_7'=>, 'Thang_8'=>,
                'Thang_9'=>, 'Thang_10'=>, 'Thang_11'=>, 'Thang_12'=>,
            ],
            ['MarketID'=> 124, 'DistrictName'=> 'Quận 10', 'WardName'=>'Phường 15', 'Year'=>'2020',
                'Thang_1'=>random_int(), 'Thang_2'=>, 'Thang_3'=>, 'Thang_4'=>,
                'Thang_5'=>, 'Thang_6'=>, 'Thang_7'=>, 'Thang_8'=>,
                'Thang_9'=>, 'Thang_10'=>, 'Thang_11'=>, 'Thang_12'=>,
            ],

            //Gia dat quan 11 - Chua edit.
            ['MarketID'=> 125, 'DistrictName'=> 'Quận 11', 'WardName'=>'Phường 01', 'Year'=>'2020',
                'Thang_1'=>random_int(), 'Thang_2'=>, 'Thang_3'=>, 'Thang_4'=>,
                'Thang_5'=>, 'Thang_6'=>, 'Thang_7'=>, 'Thang_8'=>,
                'Thang_9'=>, 'Thang_10'=>, 'Thang_11'=>, 'Thang_12'=>,
            ],
            ['MarketID'=> 126, 'DistrictName'=> 'Quận 11', 'WardName'=>'Phường 02', 'Year'=>'2020',
                'Thang_1'=>random_int(), 'Thang_2'=>, 'Thang_3'=>, 'Thang_4'=>,
                'Thang_5'=>, 'Thang_6'=>, 'Thang_7'=>, 'Thang_8'=>,
                'Thang_9'=>, 'Thang_10'=>, 'Thang_11'=>, 'Thang_12'=>,
            ],
            ['MarketID'=> 127, 'DistrictName'=> 'Quận 11', 'WardName'=>'Phường 03', 'Year'=>'2020',
                'Thang_1'=>random_int(), 'Thang_2'=>, 'Thang_3'=>, 'Thang_4'=>,
                'Thang_5'=>, 'Thang_6'=>, 'Thang_7'=>, 'Thang_8'=>,
                'Thang_9'=>, 'Thang_10'=>, 'Thang_11'=>, 'Thang_12'=>,
            ],
            ['MarketID'=> 128, 'DistrictName'=> 'Quận 11', 'WardName'=>'Phường 04', 'Year'=>'2020',
                'Thang_1'=>random_int(), 'Thang_2'=>, 'Thang_3'=>, 'Thang_4'=>,
                'Thang_5'=>, 'Thang_6'=>, 'Thang_7'=>, 'Thang_8'=>,
                'Thang_9'=>, 'Thang_10'=>, 'Thang_11'=>, 'Thang_12'=>,
            ],
            ['MarketID'=> 129, 'DistrictName'=> 'Quận 11', 'WardName'=>'Phường 05', 'Year'=>'2020',
                'Thang_1'=>random_int(), 'Thang_2'=>, 'Thang_3'=>, 'Thang_4'=>,
                'Thang_5'=>, 'Thang_6'=>, 'Thang_7'=>, 'Thang_8'=>,
                'Thang_9'=>, 'Thang_10'=>, 'Thang_11'=>, 'Thang_12'=>,
            ],
            ['MarketID'=> 130, 'DistrictName'=> 'Quận 11', 'WardName'=>'Phường 06', 'Year'=>'2020',
                'Thang_1'=>random_int(), 'Thang_2'=>, 'Thang_3'=>, 'Thang_4'=>,
                'Thang_5'=>, 'Thang_6'=>, 'Thang_7'=>, 'Thang_8'=>,
                'Thang_9'=>, 'Thang_10'=>, 'Thang_11'=>, 'Thang_12'=>,
            ],
            ['MarketID'=> 131, 'DistrictName'=> 'Quận 11', 'WardName'=>'Phường 07', 'Year'=>'2020',
                'Thang_1'=>random_int(), 'Thang_2'=>, 'Thang_3'=>, 'Thang_4'=>,
                'Thang_5'=>, 'Thang_6'=>, 'Thang_7'=>, 'Thang_8'=>,
                'Thang_9'=>, 'Thang_10'=>, 'Thang_11'=>, 'Thang_12'=>,
            ],
            ['MarketID'=> 132, 'DistrictName'=> 'Quận 11', 'WardName'=>'Phường 08', 'Year'=>'2020',
                'Thang_1'=>random_int(), 'Thang_2'=>, 'Thang_3'=>, 'Thang_4'=>,
                'Thang_5'=>, 'Thang_6'=>, 'Thang_7'=>, 'Thang_8'=>,
                'Thang_9'=>, 'Thang_10'=>, 'Thang_11'=>, 'Thang_12'=>,
            ],
            ['MarketID'=> 133, 'DistrictName'=> 'Quận 11', 'WardName'=>'Phường 09', 'Year'=>'2020',
                'Thang_1'=>random_int(), 'Thang_2'=>, 'Thang_3'=>, 'Thang_4'=>,
                'Thang_5'=>, 'Thang_6'=>, 'Thang_7'=>, 'Thang_8'=>,
                'Thang_9'=>, 'Thang_10'=>, 'Thang_11'=>, 'Thang_12'=>,
            ],
            ['MarketID'=> 134, 'DistrictName'=> 'Quận 11', 'WardName'=>'Phường 10', 'Year'=>'2020',
                'Thang_1'=>random_int(), 'Thang_2'=>, 'Thang_3'=>, 'Thang_4'=>,
                'Thang_5'=>, 'Thang_6'=>, 'Thang_7'=>, 'Thang_8'=>,
                'Thang_9'=>, 'Thang_10'=>, 'Thang_11'=>, 'Thang_12'=>,
            ],
            ['MarketID'=> 135, 'DistrictName'=> 'Quận 11', 'WardName'=>'Phường 11', 'Year'=>'2020',
                'Thang_1'=>random_int(), 'Thang_2'=>, 'Thang_3'=>, 'Thang_4'=>,
                'Thang_5'=>, 'Thang_6'=>, 'Thang_7'=>, 'Thang_8'=>,
                'Thang_9'=>, 'Thang_10'=>, 'Thang_11'=>, 'Thang_12'=>,
            ],
            ['MarketID'=> 136, 'DistrictName'=> 'Quận 11', 'WardName'=>'Phường 12', 'Year'=>'2020',
                'Thang_1'=>random_int(), 'Thang_2'=>, 'Thang_3'=>, 'Thang_4'=>,
                'Thang_5'=>, 'Thang_6'=>, 'Thang_7'=>, 'Thang_8'=>,
                'Thang_9'=>, 'Thang_10'=>, 'Thang_11'=>, 'Thang_12'=>,
            ],
            ['MarketID'=> 137, 'DistrictName'=> 'Quận 11', 'WardName'=>'Phường 13', 'Year'=>'2020',
                'Thang_1'=>random_int(), 'Thang_2'=>, 'Thang_3'=>, 'Thang_4'=>,
                'Thang_5'=>, 'Thang_6'=>, 'Thang_7'=>, 'Thang_8'=>,
                'Thang_9'=>, 'Thang_10'=>, 'Thang_11'=>, 'Thang_12'=>,
            ],
            ['MarketID'=> 138, 'DistrictName'=> 'Quận 11', 'WardName'=>'Phường 14', 'Year'=>'2020',
                'Thang_1'=>random_int(), 'Thang_2'=>, 'Thang_3'=>, 'Thang_4'=>,
                'Thang_5'=>, 'Thang_6'=>, 'Thang_7'=>, 'Thang_8'=>,
                'Thang_9'=>, 'Thang_10'=>, 'Thang_11'=>, 'Thang_12'=>,
            ],
            ['MarketID'=> 139, 'DistrictName'=> 'Quận 11', 'WardName'=>'Phường 15', 'Year'=>'2020',
                'Thang_1'=>random_int(), 'Thang_2'=>, 'Thang_3'=>, 'Thang_4'=>,
                'Thang_5'=>, 'Thang_6'=>, 'Thang_7'=>, 'Thang_8'=>,
                'Thang_9'=>, 'Thang_10'=>, 'Thang_11'=>, 'Thang_12'=>,
            ],
            ['MarketID'=> 140, 'DistrictName'=> 'Quận 11', 'WardName'=>'Phường 16', 'Year'=>'2020',
                'Thang_1'=>random_int(), 'Thang_2'=>, 'Thang_3'=>, 'Thang_4'=>,
                'Thang_5'=>, 'Thang_6'=>, 'Thang_7'=>, 'Thang_8'=>,
                'Thang_9'=>, 'Thang_10'=>, 'Thang_11'=>, 'Thang_12'=>,
            ],

            //Gia dat quan 12 - chua edit.
            ['MarketID'=> 141, 'DistrictName'=> 'Quận 12', 'WardName'=>'An Phú Đông', 'Year'=>'2020',
                'Thang_1'=>random_int(), 'Thang_2'=>, 'Thang_3'=>, 'Thang_4'=>,
                'Thang_5'=>, 'Thang_6'=>, 'Thang_7'=>, 'Thang_8'=>,
                'Thang_9'=>, 'Thang_10'=>, 'Thang_11'=>, 'Thang_12'=>,
            ],
            ['MarketID'=> 142, 'DistrictName'=> 'Quận 12', 'WardName'=>'Đông Hưng Thuận', 'Year'=>'2020',
                'Thang_1'=>random_int(), 'Thang_2'=>, 'Thang_3'=>, 'Thang_4'=>,
                'Thang_5'=>, 'Thang_6'=>, 'Thang_7'=>, 'Thang_8'=>,
                'Thang_9'=>, 'Thang_10'=>, 'Thang_11'=>, 'Thang_12'=>,
            ],
            ['MarketID'=> 143, 'DistrictName'=> 'Quận 12', 'WardName'=>'Hiệp Thành', 'Year'=>'2020',
                'Thang_1'=>random_int(), 'Thang_2'=>, 'Thang_3'=>, 'Thang_4'=>,
                'Thang_5'=>, 'Thang_6'=>, 'Thang_7'=>, 'Thang_8'=>,
                'Thang_9'=>, 'Thang_10'=>, 'Thang_11'=>, 'Thang_12'=>,
            ],
            ['MarketID'=> 144, 'DistrictName'=> 'Quận 12', 'WardName'=>'Tân Chánh Hiệp', 'Year'=>'2020',
                'Thang_1'=>random_int(), 'Thang_2'=>, 'Thang_3'=>, 'Thang_4'=>,
                'Thang_5'=>, 'Thang_6'=>, 'Thang_7'=>, 'Thang_8'=>,
                'Thang_9'=>, 'Thang_10'=>, 'Thang_11'=>, 'Thang_12'=>,
            ],
            ['MarketID'=> 145, 'DistrictName'=> 'Quận 12', 'WardName'=>'Tân Hưng Thuậ', 'Year'=>'2020',
                'Thang_1'=>random_int(), 'Thang_2'=>, 'Thang_3'=>, 'Thang_4'=>,
                'Thang_5'=>, 'Thang_6'=>, 'Thang_7'=>, 'Thang_8'=>,
                'Thang_9'=>, 'Thang_10'=>, 'Thang_11'=>, 'Thang_12'=>,
            ],
            ['MarketID'=> 146, 'DistrictName'=> 'Quận 12', 'WardName'=>'Tân Thới Hiệp', 'Year'=>'2020',
                'Thang_1'=>random_int(), 'Thang_2'=>, 'Thang_3'=>, 'Thang_4'=>,
                'Thang_5'=>, 'Thang_6'=>, 'Thang_7'=>, 'Thang_8'=>,
                'Thang_9'=>, 'Thang_10'=>, 'Thang_11'=>, 'Thang_12'=>,
            ],
            ['MarketID'=> 147, 'DistrictName'=> 'Quận 12', 'WardName'=>'Tân Thới Nhất', 'Year'=>'2020',
                'Thang_1'=>random_int(), 'Thang_2'=>, 'Thang_3'=>, 'Thang_4'=>,
                'Thang_5'=>, 'Thang_6'=>, 'Thang_7'=>, 'Thang_8'=>,
                'Thang_9'=>, 'Thang_10'=>, 'Thang_11'=>, 'Thang_12'=>,
            ],
            ['MarketID'=> 148, 'DistrictName'=> 'Quận 12', 'WardName'=>'Thạnh Lộc', 'Year'=>'2020',
                'Thang_1'=>random_int(), 'Thang_2'=>, 'Thang_3'=>, 'Thang_4'=>,
                'Thang_5'=>, 'Thang_6'=>, 'Thang_7'=>, 'Thang_8'=>,
                'Thang_9'=>, 'Thang_10'=>, 'Thang_11'=>, 'Thang_12'=>,
            ],
            ['MarketID'=> 149, 'DistrictName'=> 'Quận 12', 'WardName'=>'Thạnh Xuân', 'Year'=>'2020',
                'Thang_1'=>random_int(), 'Thang_2'=>, 'Thang_3'=>, 'Thang_4'=>,
                'Thang_5'=>, 'Thang_6'=>, 'Thang_7'=>, 'Thang_8'=>,
                'Thang_9'=>, 'Thang_10'=>, 'Thang_11'=>, 'Thang_12'=>,
            ],
            ['MarketID'=> 150, 'DistrictName'=> 'Quận 12', 'WardName'=>'Thới An', 'Year'=>'2020',
                'Thang_1'=>random_int(), 'Thang_2'=>, 'Thang_3'=>, 'Thang_4'=>,
                'Thang_5'=>, 'Thang_6'=>, 'Thang_7'=>, 'Thang_8'=>,
                'Thang_9'=>, 'Thang_10'=>, 'Thang_11'=>, 'Thang_12'=>,
            ],
            ['MarketID'=> 151, 'DistrictName'=> 'Quận 12', 'WardName'=>'Trung Mỹ Tây', 'Year'=>'2020',
                'Thang_1'=>random_int(), 'Thang_2'=>, 'Thang_3'=>, 'Thang_4'=>,
                'Thang_5'=>, 'Thang_6'=>, 'Thang_7'=>, 'Thang_8'=>,
                'Thang_9'=>, 'Thang_10'=>, 'Thang_11'=>, 'Thang_12'=>,
            ],

            //Gia đất quận Bình Tân - chưa edit.
            ['MarketID'=> 152, 'DistrictName'=> 'Quận Bình Tân', 'WardName'=>'An Lạc', 'Year'=>'2020',
                'Thang_1'=>random_int(), 'Thang_2'=>, 'Thang_3'=>, 'Thang_4'=>,
                'Thang_5'=>, 'Thang_6'=>, 'Thang_7'=>, 'Thang_8'=>,
                'Thang_9'=>, 'Thang_10'=>, 'Thang_11'=>, 'Thang_12'=>,
            ],
        ]);
    }
}
