<?php

namespace Database\Seeders\Market;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class WardList extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        DB::table('ward_lists')->insert([

        //mở comment trước khi update data, sau khi update khóa comment để tránh bị lỗi lần sau.

//            //update các phường quận 1.
//            ['WardID'=>'1',  'DistrictName'=> 'Quận 1', 'WardName'=>'Bến Nghé'],
//            ['WardID'=>'2',  'DistrictName'=> 'Quận 1', 'WardName'=>'Bến Thành'],
//            ['WardID'=>'3',  'DistrictName'=> 'Quận 1', 'WardName'=>'Cầu Kho'],
//            ['WardID'=>'4',  'DistrictName'=> 'Quận 1', 'WardName'=>'Cầu Ông Lãnh'],
//            ['WardID'=>'5',  'DistrictName'=> 'Quận 1', 'WardName'=>'Cô Giang'],
//            ['WardID'=>'6',  'DistrictName'=> 'Quận 1', 'WardName'=>'Đa Kao'],
//            ['WardID'=>'7',  'DistrictName'=> 'Quận 1', 'WardName'=>'Nguyễn Cư Trinh'],
//            ['WardID'=>'8',  'DistrictName'=> 'Quận 1', 'WardName'=>'Nguyễn Thái Bình'],
//            ['WardID'=>'9',  'DistrictName'=> 'Quận 1', 'WardName'=>'Phạm Ngũ Lão'],
//            ['WardID'=>'10', 'DistrictName'=> 'Quận 1', 'WardName'=>'Tân Định'],
//
//            //update các phường quận 2.
//            ['WardID'=>'11', 'DistrictName'=> 'Quận 2', 'WardName'=>'An Khánh'],
//            ['WardID'=>'12', 'DistrictName'=> 'Quận 2', 'WardName'=>'An Lợi Đông'],
//            ['WardID'=>'13', 'DistrictName'=> 'Quận 2', 'WardName'=>'An Phú'],
//            ['WardID'=>'14', 'DistrictName'=> 'Quận 2', 'WardName'=>'Bình An'],
//            ['WardID'=>'15', 'DistrictName'=> 'Quận 2', 'WardName'=>'Bình Khánh'],
//            ['WardID'=>'16', 'DistrictName'=> 'Quận 2', 'WardName'=>'Bình Trưng Đông'],
//            ['WardID'=>'17', 'DistrictName'=> 'Quận 2', 'WardName'=>'Bình Trưng Tây'],
//            ['WardID'=>'18', 'DistrictName'=> 'Quận 2', 'WardName'=>'Cát Lái'],
//            ['WardID'=>'19', 'DistrictName'=> 'Quận 2', 'WardName'=>'Thạnh Mỹ Lợi'],
//            ['WardID'=>'20', 'DistrictName'=> 'Quận 2', 'WardName'=>'Thảo Điền'],
//            ['WardID'=>'21', 'DistrictName'=> 'Quận 2', 'WardName'=>'Thủ Thiêm'],
//
//            //update các phường quận 3.
//            ['WardID'=>'23', 'DistrictName'=> 'Quận 3', 'WardName'=>'Phường 01'],
//            ['WardID'=>'24', 'DistrictName'=> 'Quận 3', 'WardName'=>'Phường 02'],
//            ['WardID'=>'25', 'DistrictName'=> 'Quận 3', 'WardName'=>'Phường 03'],
//            ['WardID'=>'26', 'DistrictName'=> 'Quận 3', 'WardName'=>'Phường 04'],
//            ['WardID'=>'27', 'DistrictName'=> 'Quận 3', 'WardName'=>'Phường 05'],
//            ['WardID'=>'28', 'DistrictName'=> 'Quận 3', 'WardName'=>'Phường 06'],
//            ['WardID'=>'29', 'DistrictName'=> 'Quận 3', 'WardName'=>'Phường 07'],
//            ['WardID'=>'30', 'DistrictName'=> 'Quận 3', 'WardName'=>'Phường 08'],
//            ['WardID'=>'31', 'DistrictName'=> 'Quận 3', 'WardName'=>'Phường 09'],
//            ['WardID'=>'32', 'DistrictName'=> 'Quận 3', 'WardName'=>'Phường 10'],
//            ['WardID'=>'33', 'DistrictName'=> 'Quận 3', 'WardName'=>'Phường 11'],
//            ['WardID'=>'34', 'DistrictName'=> 'Quận 3', 'WardName'=>'Phường 12'],
//            ['WardID'=>'35', 'DistrictName'=> 'Quận 3', 'WardName'=>'Phường 13'],
//            ['WardID'=>'36', 'DistrictName'=> 'Quận 3', 'WardName'=>'Phường 14'],
//
//            //update các phường quận 4.
//            ['WardID'=>'37', 'DistrictName'=> 'Quận 4', 'WardName'=>'Phường 01'],
//            ['WardID'=>'38', 'DistrictName'=> 'Quận 4', 'WardName'=>'Phường 02'],
//            ['WardID'=>'39', 'DistrictName'=> 'Quận 4', 'WardName'=>'Phường 03'],
//            ['WardID'=>'40', 'DistrictName'=> 'Quận 4', 'WardName'=>'Phường 04'],
//            ['WardID'=>'41', 'DistrictName'=> 'Quận 4', 'WardName'=>'Phường 05'],
//            ['WardID'=>'42', 'DistrictName'=> 'Quận 4', 'WardName'=>'Phường 06'],
//            ['WardID'=>'44', 'DistrictName'=> 'Quận 4', 'WardName'=>'Phường 08'],
//            ['WardID'=>'45', 'DistrictName'=> 'Quận 4', 'WardName'=>'Phường 09'],
//            ['WardID'=>'46', 'DistrictName'=> 'Quận 4', 'WardName'=>'Phường 10'],
//            ['WardID'=>'48', 'DistrictName'=> 'Quận 4', 'WardName'=>'Phường 12'],
//            ['WardID'=>'49', 'DistrictName'=> 'Quận 4', 'WardName'=>'Phường 13'],
//            ['WardID'=>'50', 'DistrictName'=> 'Quận 4', 'WardName'=>'Phường 14'],
//            ['WardID'=>'51', 'DistrictName'=> 'Quận 4', 'WardName'=>'Phường 15'],
//            ['WardID'=>'52', 'DistrictName'=> 'Quận 4', 'WardName'=>'Phường 16'],
//            ['WardID'=>'54', 'DistrictName'=> 'Quận 4', 'WardName'=>'Phường 18'],
//
////            update các phường quận 5.
//            ['WardID'=>'55', 'DistrictName'=> 'Quận 5', 'WardName'=>'Phường 01'],
//            ['WardID'=>'56', 'DistrictName'=> 'Quận 5', 'WardName'=>'Phường 02'],
//            ['WardID'=>'57', 'DistrictName'=> 'Quận 5', 'WardName'=>'Phường 03'],
//            ['WardID'=>'58', 'DistrictName'=> 'Quận 5', 'WardName'=>'Phường 04'],
//            ['WardID'=>'59', 'DistrictName'=> 'Quận 5', 'WardName'=>'Phường 05'],
//            ['WardID'=>'60', 'DistrictName'=> 'Quận 5', 'WardName'=>'Phường 06'],
//            ['WardID'=>'61', 'DistrictName'=> 'Quận 5', 'WardName'=>'Phường 07'],
//            ['WardID'=>'62', 'DistrictName'=> 'Quận 5', 'WardName'=>'Phường 08'],
//            ['WardID'=>'63', 'DistrictName'=> 'Quận 5', 'WardName'=>'Phường 09'],
//            ['WardID'=>'64', 'DistrictName'=> 'Quận 5', 'WardName'=>'Phường 10'],
//            ['WardID'=>'65', 'DistrictName'=> 'Quận 5', 'WardName'=>'Phường 11'],
//            ['WardID'=>'66', 'DistrictName'=> 'Quận 5', 'WardName'=>'Phường 12'],
//            ['WardID'=>'67', 'DistrictName'=> 'Quận 5', 'WardName'=>'Phường 13'],
//            ['WardID'=>'68', 'DistrictName'=> 'Quận 5', 'WardName'=>'Phường 14'],
//            ['WardID'=>'69', 'DistrictName'=> 'Quận 5', 'WardName'=>'Phường 15'],
//
//            //update các phường quận 6.
//            ['WardID'=>'70', 'DistrictName'=> 'Quận 6', 'WardName'=>'Phường 01'],
//            ['WardID'=>'71', 'DistrictName'=> 'Quận 6', 'WardName'=>'Phường 02'],
//            ['WardID'=>'72', 'DistrictName'=> 'Quận 6', 'WardName'=>'Phường 03'],
//            ['WardID'=>'73', 'DistrictName'=> 'Quận 6', 'WardName'=>'Phường 04'],
//            ['WardID'=>'74', 'DistrictName'=> 'Quận 6', 'WardName'=>'Phường 05'],
//            ['WardID'=>'75', 'DistrictName'=> 'Quận 6', 'WardName'=>'Phường 06'],
//            ['WardID'=>'76', 'DistrictName'=> 'Quận 6', 'WardName'=>'Phường 07'],
//            ['WardID'=>'77', 'DistrictName'=> 'Quận 6', 'WardName'=>'Phường 08'],
//            ['WardID'=>'78', 'DistrictName'=> 'Quận 6', 'WardName'=>'Phường 09'],
//            ['WardID'=>'79', 'DistrictName'=> 'Quận 6', 'WardName'=>'Phường 10'],
//            ['WardID'=>'80', 'DistrictName'=> 'Quận 6', 'WardName'=>'Phường 11'],
//            ['WardID'=>'81', 'DistrictName'=> 'Quận 6', 'WardName'=>'Phường 12'],
//            ['WardID'=>'82', 'DistrictName'=> 'Quận 6', 'WardName'=>'Phường 13'],
//            ['WardID'=>'83', 'DistrictName'=> 'Quận 6', 'WardName'=>'Phường 14'],
//
//            //update các phường quận 7.
//            ['WardID'=>'84', 'DistrictName'=> 'Quận 7', 'WardName'=>'Bình Thuận'],
//            ['WardID'=>'85', 'DistrictName'=> 'Quận 7', 'WardName'=>'Phú Mỹ'],
//            ['WardID'=>'86', 'DistrictName'=> 'Quận 7', 'WardName'=>'Phú Thuận'],
//            ['WardID'=>'87', 'DistrictName'=> 'Quận 7', 'WardName'=>'Tân Hưng'],
//            ['WardID'=>'88', 'DistrictName'=> 'Quận 7', 'WardName'=>'Tân Kiểng'],
//            ['WardID'=>'89', 'DistrictName'=> 'Quận 7', 'WardName'=>'Tân Phong'],
//            ['WardID'=>'90', 'DistrictName'=> 'Quận 7', 'WardName'=>'Tân Phú'],
//            ['WardID'=>'91', 'DistrictName'=> 'Quận 7', 'WardName'=>'Tân Quy'],
//            ['WardID'=>'92', 'DistrictName'=> 'Quận 7', 'WardName'=>'Tân Thuận Đông'],
//            ['WardID'=>'93', 'DistrictName'=> 'Quận 7', 'WardName'=>'Tân Thuận Tây'],

//            //update các phường quận 8.
//            ['WardID'=>'94', 'DistrictName'=> 'Quận 8', 'WardName'=>'Phường 01'],
//            ['WardID'=>'95', 'DistrictName'=> 'Quận 8', 'WardName'=>'Phường 02'],
//            ['WardID'=>'96', 'DistrictName'=> 'Quận 8', 'WardName'=>'Phường 03'],
//            ['WardID'=>'97', 'DistrictName'=> 'Quận 8', 'WardName'=>'Phường 04'],
//            ['WardID'=>'98', 'DistrictName'=> 'Quận 8', 'WardName'=>'Phường 05'],
//            ['WardID'=>'99', 'DistrictName'=> 'Quận 8', 'WardName'=>'Phường 06'],
//            ['WardID'=>'100', 'DistrictName'=> 'Quận 8', 'WardName'=>'Phường 07'],
//            ['WardID'=>'101', 'DistrictName'=> 'Quận 8', 'WardName'=>'Phường 08'],
//            ['WardID'=>'102', 'DistrictName'=> 'Quận 8', 'WardName'=>'Phường 09'],
//            ['WardID'=>'103', 'DistrictName'=> 'Quận 8', 'WardName'=>'Phường 10'],
//            ['WardID'=>'104', 'DistrictName'=> 'Quận 8', 'WardName'=>'Phường 11'],
//            ['WardID'=>'105', 'DistrictName'=> 'Quận 8', 'WardName'=>'Phường 12'],
//            ['WardID'=>'106', 'DistrictName'=> 'Quận 8', 'WardName'=>'Phường 13'],
//            ['WardID'=>'107', 'DistrictName'=> 'Quận 8', 'WardName'=>'Phường 14'],
//            ['WardID'=>'108', 'DistrictName'=> 'Quận 8', 'WardName'=>'Phường 15'],
//            ['WardID'=>'109', 'DistrictName'=> 'Quận 8', 'WardName'=>'Phường 16'],
//
//            //update các phường quận 10.
//            ['WardID'=>'110', 'DistrictName'=> 'Quận 10', 'WardName'=>'Phường 01'],
//            ['WardID'=>'111', 'DistrictName'=> 'Quận 10', 'WardName'=>'Phường 02'],
//            ['WardID'=>'112', 'DistrictName'=> 'Quận 10', 'WardName'=>'Phường 03'],
//            ['WardID'=>'113', 'DistrictName'=> 'Quận 10', 'WardName'=>'Phường 04'],
//            ['WardID'=>'114', 'DistrictName'=> 'Quận 10', 'WardName'=>'Phường 05'],
//            ['WardID'=>'115', 'DistrictName'=> 'Quận 10', 'WardName'=>'Phường 06'],
//            ['WardID'=>'116', 'DistrictName'=> 'Quận 10', 'WardName'=>'Phường 07'],
//            ['WardID'=>'117', 'DistrictName'=> 'Quận 10', 'WardName'=>'Phường 08'],
//            ['WardID'=>'118', 'DistrictName'=> 'Quận 10', 'WardName'=>'Phường 09'],
//            ['WardID'=>'119', 'DistrictName'=> 'Quận 10', 'WardName'=>'Phường 10'],
//            ['WardID'=>'120', 'DistrictName'=> 'Quận 10', 'WardName'=>'Phường 11'],
//            ['WardID'=>'121', 'DistrictName'=> 'Quận 10', 'WardName'=>'Phường 12'],
//            ['WardID'=>'122', 'DistrictName'=> 'Quận 10', 'WardName'=>'Phường 13'],
//            ['WardID'=>'123', 'DistrictName'=> 'Quận 10', 'WardName'=>'Phường 14'],
//            ['WardID'=>'124', 'DistrictName'=> 'Quận 10', 'WardName'=>'Phường 15'],
//
//            //update các phường quận 11.
//            ['WardID'=>'125', 'DistrictName'=> 'Quận 11', 'WardName'=>'Phường 01'],
//            ['WardID'=>'126', 'DistrictName'=> 'Quận 11', 'WardName'=>'Phường 02'],
//            ['WardID'=>'127', 'DistrictName'=> 'Quận 11', 'WardName'=>'Phường 03'],
//            ['WardID'=>'128', 'DistrictName'=> 'Quận 11', 'WardName'=>'Phường 04'],
//            ['WardID'=>'129', 'DistrictName'=> 'Quận 11', 'WardName'=>'Phường 05'],
//            ['WardID'=>'130', 'DistrictName'=> 'Quận 11', 'WardName'=>'Phường 06'],
//            ['WardID'=>'131', 'DistrictName'=> 'Quận 11', 'WardName'=>'Phường 07'],
//            ['WardID'=>'132', 'DistrictName'=> 'Quận 11', 'WardName'=>'Phường 08'],
//            ['WardID'=>'133', 'DistrictName'=> 'Quận 11', 'WardName'=>'Phường 09'],
//            ['WardID'=>'134', 'DistrictName'=> 'Quận 11', 'WardName'=>'Phường 10'],
//            ['WardID'=>'135', 'DistrictName'=> 'Quận 11', 'WardName'=>'Phường 11'],
//            ['WardID'=>'136', 'DistrictName'=> 'Quận 11', 'WardName'=>'Phường 12'],
//            ['WardID'=>'137', 'DistrictName'=> 'Quận 11', 'WardName'=>'Phường 13'],
//            ['WardID'=>'138', 'DistrictName'=> 'Quận 11', 'WardName'=>'Phường 14'],
//            ['WardID'=>'139', 'DistrictName'=> 'Quận 11', 'WardName'=>'Phường 15'],
//            ['WardID'=>'140', 'DistrictName'=> 'Quận 11', 'WardName'=>'Phường 16'],
//
//            //update các phường quận 12.
//            ['WardID'=>'141', 'DistrictName'=> 'Quận 12', 'WardName'=>'An Phú Đông'],
//            ['WardID'=>'142', 'DistrictName'=> 'Quận 12', 'WardName'=>'Đông Hưng Thuận'],
//            ['WardID'=>'143', 'DistrictName'=> 'Quận 12', 'WardName'=>'Hiệp Thành'],
//            ['WardID'=>'144', 'DistrictName'=> 'Quận 12', 'WardName'=>'Tân Chánh Hiệp'],
//            ['WardID'=>'145', 'DistrictName'=> 'Quận 12', 'WardName'=>'Tân Hưng Thuận'],
//            ['WardID'=>'146', 'DistrictName'=> 'Quận 12', 'WardName'=>'Tân Thới Hiệp'],
//            ['WardID'=>'147', 'DistrictName'=> 'Quận 12', 'WardName'=>'Tân Thới Nhất'],
//            ['WardID'=>'148', 'DistrictName'=> 'Quận 12', 'WardName'=>'Thạnh Lộc'],
//            ['WardID'=>'149', 'DistrictName'=> 'Quận 12', 'WardName'=>'Thạnh Xuân'],
//            ['WardID'=>'150', 'DistrictName'=> 'Quận 12', 'WardName'=>'Thới An'],
//            ['WardID'=>'151', 'DistrictName'=> 'Quận 12', 'WardName'=>'Trung Mỹ Tây'],
//
////            update các phường quận bình tân.
//            ['WardID'=>'152', 'DistrictName'=> 'Quận Bình Tân', 'WardName'=>'An Lạc'],
//            ['WardID'=>'153', 'DistrictName'=> 'Quận Bình Tân', 'WardName'=>'An Lạc A'],
//            ['WardID'=>'154', 'DistrictName'=> 'Quận Bình Tân', 'WardName'=>'Bình Hưng Hòa'],
//            ['WardID'=>'155', 'DistrictName'=> 'Quận Bình Tân', 'WardName'=>'Bình Hưng Hoà A'],
//            ['WardID'=>'156', 'DistrictName'=> 'Quận Bình Tân', 'WardName'=>'Bình Hưng Hoà B'],
//            ['WardID'=>'157', 'DistrictName'=> 'Quận Bình Tân', 'WardName'=>'Bình Trị Đôngc'],
//            ['WardID'=>'158', 'DistrictName'=> 'Quận Bình Tân', 'WardName'=>'Bình Trị Đông A'],
//            ['WardID'=>'159', 'DistrictName'=> 'Quận Bình Tân', 'WardName'=>'Bình Trị Đông B'],
//            ['WardID'=>'160', 'DistrictName'=> 'Quận Bình Tân', 'WardName'=>'Phường Tân Tạo'],
//            ['WardID'=>'161', 'DistrictName'=> 'Quận Bình Tân', 'WardName'=>'Phường Tân Tạo A'],
//
////            update các phường quận bình Thạnh.
//            ['WardID'=>'162', 'DistrictName'=> 'Quận Bình Thạnh', 'WardName'=>'Phường 01'],
//            ['WardID'=>'163', 'DistrictName'=> 'Quận Bình Thạnh', 'WardName'=>'Phường 02'],
//            ['WardID'=>'164', 'DistrictName'=> 'Quận Bình Thạnh', 'WardName'=>'Phường 03'],
//            ['WardID'=>'165', 'DistrictName'=> 'Quận Bình Thạnh', 'WardName'=>'Phường 04'],
//            ['WardID'=>'166', 'DistrictName'=> 'Quận Bình Thạnh', 'WardName'=>'Phường 05'],
//            ['WardID'=>'167', 'DistrictName'=> 'Quận Bình Thạnh', 'WardName'=>'Phường 06'],
//            ['WardID'=>'168', 'DistrictName'=> 'Quận Bình Thạnh', 'WardName'=>'Phường 07'],
//            ['WardID'=>'169', 'DistrictName'=> 'Quận Bình Thạnh', 'WardName'=>'Phường 08'],
//            ['WardID'=>'170', 'DistrictName'=> 'Quận Bình Thạnh', 'WardName'=>'Phường 09'],
//            ['WardID'=>'171', 'DistrictName'=> 'Quận Bình Thạnh', 'WardName'=>'Phường 10'],
//            ['WardID'=>'172', 'DistrictName'=> 'Quận Bình Thạnh', 'WardName'=>'Phường 11'],
//            ['WardID'=>'173', 'DistrictName'=> 'Quận Bình Thạnh', 'WardName'=>'Phường 12'],
//            ['WardID'=>'174', 'DistrictName'=> 'Quận Bình Thạnh', 'WardName'=>'Phường 13'],
//            ['WardID'=>'175', 'DistrictName'=> 'Quận Bình Thạnh', 'WardName'=>'Phường 14'],
//            ['WardID'=>'176', 'DistrictName'=> 'Quận Bình Thạnh', 'WardName'=>'Phường 15'],
//            ['WardID'=>'177', 'DistrictName'=> 'Quận Bình Thạnh', 'WardName'=>'Phường 16'],
//            ['WardID'=>'178', 'DistrictName'=> 'Quận Bình Thạnh', 'WardName'=>'Phường 17'],
//            ['WardID'=>'179', 'DistrictName'=> 'Quận Bình Thạnh', 'WardName'=>'Phường 18'],
//            ['WardID'=>'180', 'DistrictName'=> 'Quận Bình Thạnh', 'WardName'=>'Phường 19'],
//            ['WardID'=>'181', 'DistrictName'=> 'Quận Bình Thạnh', 'WardName'=>'Phường 20'],
//            ['WardID'=>'182', 'DistrictName'=> 'Quận Bình Thạnh', 'WardName'=>'Phường 21'],
//            ['WardID'=>'183', 'DistrictName'=> 'Quận Bình Thạnh', 'WardName'=>'Phường 22'],
//            ['WardID'=>'184', 'DistrictName'=> 'Quận Bình Thạnh', 'WardName'=>'Phường 23'],
//            ['WardID'=>'185', 'DistrictName'=> 'Quận Bình Thạnh', 'WardName'=>'Phường 24'],
//            ['WardID'=>'186', 'DistrictName'=> 'Quận Bình Thạnh', 'WardName'=>'Phường 25'],
//            ['WardID'=>'187', 'DistrictName'=> 'Quận Bình Thạnh', 'WardName'=>'Phường 26'],
//            ['WardID'=>'188', 'DistrictName'=> 'Quận Bình Thạnh', 'WardName'=>'Phường 27'],
//            ['WardID'=>'189', 'DistrictName'=> 'Quận Bình Thạnh', 'WardName'=>'Phường 28'],
//
////            update các phường quận Gò Vấp.
//            ['WardID'=>'190', 'DistrictName'=> 'Quận Gò Vấp', 'WardName'=>'Phường 01'],
//            ['WardID'=>'191', 'DistrictName'=> 'Quận Gò Vấp', 'WardName'=>'Phường 02'],
//            ['WardID'=>'192', 'DistrictName'=> 'Quận Gò Vấp', 'WardName'=>'Phường 03'],
//            ['WardID'=>'193', 'DistrictName'=> 'Quận Gò Vấp', 'WardName'=>'Phường 04'],
//            ['WardID'=>'194', 'DistrictName'=> 'Quận Gò Vấp', 'WardName'=>'Phường 05'],
//            ['WardID'=>'195', 'DistrictName'=> 'Quận Gò Vấp', 'WardName'=>'Phường 06'],
//            ['WardID'=>'196', 'DistrictName'=> 'Quận Gò Vấp', 'WardName'=>'Phường 07'],
//            ['WardID'=>'197', 'DistrictName'=> 'Quận Gò Vấp', 'WardName'=>'Phường 08'],
//            ['WardID'=>'198', 'DistrictName'=> 'Quận Gò Vấp', 'WardName'=>'Phường 09'],
//            ['WardID'=>'199', 'DistrictName'=> 'Quận Gò Vấp', 'WardName'=>'Phường 10'],
//            ['WardID'=>'200', 'DistrictName'=> 'Quận Gò Vấp', 'WardName'=>'Phường 11'],
//            ['WardID'=>'201', 'DistrictName'=> 'Quận Gò Vấp', 'WardName'=>'Phường 12'],
//            ['WardID'=>'202', 'DistrictName'=> 'Quận Gò Vấp', 'WardName'=>'Phường 13'],
//            ['WardID'=>'203', 'DistrictName'=> 'Quận Gò Vấp', 'WardName'=>'Phường 14'],
//            ['WardID'=>'204', 'DistrictName'=> 'Quận Gò Vấp', 'WardName'=>'Phường 15'],
//            ['WardID'=>'205', 'DistrictName'=> 'Quận Gò Vấp', 'WardName'=>'Phường 16'],
//            ['WardID'=>'206', 'DistrictName'=> 'Quận Gò Vấp', 'WardName'=>'Phường 17'],

////            update các phường quận Phú Nhuận.
//            ['WardID'=>'207', 'DistrictName'=> 'Quận Phú Nhuận', 'WardName'=>'Phường 01'],
//            ['WardID'=>'208', 'DistrictName'=> 'Quận Phú Nhuận', 'WardName'=>'Phường 02'],
//            ['WardID'=>'209', 'DistrictName'=> 'Quận Phú Nhuận', 'WardName'=>'Phường 03'],
//            ['WardID'=>'210', 'DistrictName'=> 'Quận Phú Nhuận', 'WardName'=>'Phường 04'],
//            ['WardID'=>'211', 'DistrictName'=> 'Quận Phú Nhuận', 'WardName'=>'Phường 05'],
//            ['WardID'=>'212', 'DistrictName'=> 'Quận Phú Nhuận', 'WardName'=>'Phường 06'],
//            ['WardID'=>'213', 'DistrictName'=> 'Quận Phú Nhuận', 'WardName'=>'Phường 07'],
//            ['WardID'=>'214', 'DistrictName'=> 'Quận Phú Nhuận', 'WardName'=>'Phường 08'],
//            ['WardID'=>'215', 'DistrictName'=> 'Quận Phú Nhuận', 'WardName'=>'Phường 09'],
//            ['WardID'=>'216', 'DistrictName'=> 'Quận Phú Nhuận', 'WardName'=>'Phường 10'],
//            ['WardID'=>'217', 'DistrictName'=> 'Quận Phú Nhuận', 'WardName'=>'Phường 11'],
//            ['WardID'=>'218', 'DistrictName'=> 'Quận Phú Nhuận', 'WardName'=>'Phường 12'],
//            ['WardID'=>'219', 'DistrictName'=> 'Quận Phú Nhuận', 'WardName'=>'Phường 13'],
//            ['WardID'=>'220', 'DistrictName'=> 'Quận Phú Nhuận', 'WardName'=>'Phường 14'],
//            ['WardID'=>'221', 'DistrictName'=> 'Quận Phú Nhuận', 'WardName'=>'Phường 15'],
//            ['WardID'=>'222', 'DistrictName'=> 'Quận Phú Nhuận', 'WardName'=>'Phường 16'],
//            ['WardID'=>'223', 'DistrictName'=> 'Quận Phú Nhuận', 'WardName'=>'Phường 17'],
//
////            update các phường quận Tân Bình.
//            ['WardID'=>'224', 'DistrictName'=> 'Quận Tân Bình', 'WardName'=>'Phường 01'],
//            ['WardID'=>'225', 'DistrictName'=> 'Quận Tân Bình', 'WardName'=>'Phường 02'],
//            ['WardID'=>'226', 'DistrictName'=> 'Quận Tân Bình', 'WardName'=>'Phường 03'],
//            ['WardID'=>'227', 'DistrictName'=> 'Quận Tân Bình', 'WardName'=>'Phường 04'],
//            ['WardID'=>'228', 'DistrictName'=> 'Quận Tân Bình', 'WardName'=>'Phường 05'],
//            ['WardID'=>'229', 'DistrictName'=> 'Quận Tân Bình', 'WardName'=>'Phường 06'],
//            ['WardID'=>'230', 'DistrictName'=> 'Quận Tân Bình', 'WardName'=>'Phường 07'],
//            ['WardID'=>'231', 'DistrictName'=> 'Quận Tân Bình', 'WardName'=>'Phường 08'],
//            ['WardID'=>'232', 'DistrictName'=> 'Quận Tân Bình', 'WardName'=>'Phường 09'],
//            ['WardID'=>'233', 'DistrictName'=> 'Quận Tân Bình', 'WardName'=>'Phường 10'],
//            ['WardID'=>'234', 'DistrictName'=> 'Quận Tân Bình', 'WardName'=>'Phường 11'],
//            ['WardID'=>'235', 'DistrictName'=> 'Quận Tân Bình', 'WardName'=>'Phường 12'],
//            ['WardID'=>'236', 'DistrictName'=> 'Quận Tân Bình', 'WardName'=>'Phường 13'],
//            ['WardID'=>'237', 'DistrictName'=> 'Quận Tân Bình', 'WardName'=>'Phường 14'],
//            ['WardID'=>'238', 'DistrictName'=> 'Quận Tân Bình', 'WardName'=>'Phường 15'],

////            update các phường quận Tân Phú.
//            ['WardID'=>'239', 'DistrictName'=> 'Quận Tân Phú', 'WardName'=>'Hiệp Tân'],
//            ['WardID'=>'240', 'DistrictName'=> 'Quận Tân Phú', 'WardName'=>'Hoà Thạnh'],
//            ['WardID'=>'241', 'DistrictName'=> 'Quận Tân Phú', 'WardName'=>'Phú Thạnh'],
//            ['WardID'=>'242', 'DistrictName'=> 'Quận Tân Phú', 'WardName'=>'Phú Thọ Hoà'],
//            ['WardID'=>'243', 'DistrictName'=> 'Quận Tân Phú', 'WardName'=>'Phú Trung'],
//            ['WardID'=>'244', 'DistrictName'=> 'Quận Tân Phú', 'WardName'=>'Sơn Kỳ'],
//            ['WardID'=>'245', 'DistrictName'=> 'Quận Tân Phú', 'WardName'=>'Tân Qúy'],
//            ['WardID'=>'246', 'DistrictName'=> 'Quận Tân Phú', 'WardName'=>'Tân Sơn Nhì'],
//            ['WardID'=>'247', 'DistrictName'=> 'Quận Tân Phú', 'WardName'=>'Tân Thành'],
//            ['WardID'=>'248', 'DistrictName'=> 'Quận Tân Phú', 'WardName'=>'Tân Thới Hoà'],
//            ['WardID'=>'249', 'DistrictName'=> 'Quận Tân Phú', 'WardName'=>'Tây Thạnh'],

        ]);
    }
}
